


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.text.StyledEditorKit.ForegroundAction;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class ExtractingSocialMediaLinks {

	public static void main(String[] args)  {
		int count=0;
		List<String> urls=new ArrayList<String>();
		
		urls.add("	https://www.ubicare.com/		");
		urls.add("	https://www.ramtechnologiesinc.com/		");
		urls.add("	http://www.blueware.us		");
		urls.add("	http://planetecg.com/		");
		urls.add("	https://www.intake.me/		");
		urls.add("	https://www.aircareapp.com/		");
		urls.add("	http://professionalperformance.ca		");
		urls.add("	http://www.fortunamedical.com		");
		urls.add("	https://www.ayogo.com/		");
		urls.add("	https://www.myappworx.com/		");
		urls.add("	https://www.ebsolutions.com/		");
		urls.add("	http://caretechsys.com/		");
		urls.add("	https://www.meditelecare.com		");
		urls.add("	http://www.in-sight.net/		");
		urls.add("	https://www.sotelemed.com/		");
		urls.add("	http://www.innovatient.com/cgi-sys/suspendedpage.cgi		");
		urls.add("	https://thessigroup.com/		");
		urls.add("	https://www.realtimemedical.com/		");
		urls.add("	http://www.acrendo.com/		");
		urls.add("	https://www.officemate.net		");
		urls.add("	https://www.choiceoneehr.com/		");
		urls.add("	https://www.altapoint.com/		");
		urls.add("	http://www.chartware.com		");
		urls.add("	http://www.emr-electronicmedicalrecords.com/		");
		urls.add("	http://www.emr-electronicmedicalrecords.com/		");
		urls.add("	https://isalushealthcare.com/		");
		urls.add("	http://www.mdland.com/		");
		urls.add("	http://eclipsepracticemanagementsoftware.com/		");
		urls.add("	http://www.picofemto.com		");
		urls.add("	https://amplioncare.com/		");
		urls.add("	https://www.broadjumpllc.com/		");
		urls.add("	http://www.ht-llc.com		");
		urls.add("	https://dovetail.co/		");
		urls.add("	https://www.vigilance.ca/		");
		urls.add("	http://www.meditrax.com		");
		urls.add("	http://www.easybill.com		");
		urls.add("	https://www.abelsoft.com/		");
		urls.add("	https://www.omnimed.com/		");
		urls.add("	http://www.ebmcare.com		");
		urls.add("	https://www.mihealth.com:443/		");
		urls.add("	http://www.cycom.com		");
		urls.add("	https://www.dapasoft.com/		");
		urls.add("	https://www.bluelightanalytics.com		");
		urls.add("	http://www.therapeuticmonitoring.com		");
		urls.add("	http://www.viatronix.com		");
		urls.add("	https://www.omnipacs.com:443/		");
		urls.add("	https://www.dementiaguide.com/		");
		urls.add("	http://www.mavenlive.com		");
		urls.add("	https://www.clinicaid.ca/		");
		urls.add("	https://www.radrounds.com/		");
		urls.add("	https://www.planetrehab.com/		");
		urls.add("	https://www.digitalphysician.com:443/		");
		urls.add("	http://www.medicalmime.com		");
		urls.add("	http://www.group.md		");
		urls.add("	https://www.practiceperfectemr.com/		");
		urls.add("	https://triceimaging.com/		");
		urls.add("	http://liberatehealth.us/		");
		urls.add("	http://www.accesspsych.com		");
		urls.add("	https://www.q-reviews.com/		");
		urls.add("	http://www.drawmd.com		");
		urls.add("	http://www.marcafuture.com		");
		urls.add("	http://www.mdlmedical.com		");
		urls.add("	https://www.patient-education.com/		");
		urls.add("	http://www.mdagree.com		");
		urls.add("	https://www.avicenna-medical.com/		");
		urls.add("	https://guardianehealthsolutions.com		");
		urls.add("	http://www.abptinc.com		");
		urls.add("	https://www.sensorytech.ca/		");
		urls.add("	https://www.consult-pro.com/		");
		urls.add("	http://www.intrahealth.ca		");
		urls.add("	http://www.theobjects.com/orsvisual/		");
		urls.add("	http://www.emrlogic.com		");
		urls.add("	https://stratahealth.com/		");
		urls.add("	https://www.simpleadmit.com/		");
		urls.add("	http://www.babysentry.com		");
		urls.add("	http://www.medvision-solutions.com		");
		urls.add("	http://www.firstmedicalsolutions.com/fms/index.php		");
		urls.add("	https://www.arbormetrix.com/		");
		urls.add("	https://www.pcc.com/		");
		urls.add("	https://aegle.co/		");
		urls.add("	https://www.lifewiregroup.com/		");
		urls.add("	https://www.moberg.com/		");
		urls.add("	https://www.novatross.com/		");
		urls.add("	http://www.intersecthealth.net		");
		urls.add("	http://www.scriptrx.com		");
		urls.add("	http://www.newtechsys.com		");
		urls.add("	https://mingleanalytics.com/		");
		urls.add("	http://www.choice-hs.com		");
		urls.add("	https://www.radiustoday.com/		");
		urls.add("	https://www3.viiad.com/home		");
		urls.add("	http://www.pri-med.com		");
		urls.add("	http://www.ahconline.com/		");
		urls.add("	https://www.softworksgroup.com/		");
		urls.add("	http://www.mdconnection.com		");
		urls.add("	https://www.thesullivangroup.com/rsqsolutions/		");
		urls.add("	http://www.alphahealthcare.ca/it/		");
		urls.add("	http://crystalpm.com/		");
		urls.add("	http://www.careskore.com		");
		urls.add("	https://www.cosmetisuite.com/		");
		urls.add("	http://www.mdware.com		");
		urls.add("	http://www.simtabs.com		");
		urls.add("	http://beamme.com/		");
		urls.add("	https://www.clinicall.com/		");
		urls.add("	http://www.agastha.com		");
		urls.add("	http://www.esh.ca		");
		urls.add("	http://www.h4-technology.com/		");
		urls.add("	https://www.jethealthsolutions.com/		");
		urls.add("	https://www.liquidehr.com/		");
		urls.add("	http://www.onemedicalpassportcompany.com/		");
		urls.add("	https://www.microquest.ca/		");
		urls.add("	http://nasiff.com/		");
		urls.add("	http://www.oncare.net/		");
		urls.add("	https://www.pdmi.com/		");
		urls.add("	http://www.scriptnetics.com/		");
		urls.add("	http://therounds.com		");
		urls.add("	https://www.trigramtech.com/		");
		urls.add("	https://www.herfertsoftware.com/		");
		urls.add("	http://www.ihealthanalytics.com/		");
		urls.add("	https://www.optosys.ca/		");
		urls.add("	https://www.platinumsystembilling.com/		");
		urls.add("	http://www.statsystems.com/		");
		urls.add("	http://www.eblucare.com/		");
		urls.add("	http://patienttrac.com		");
		urls.add("	http://www.ibeza.net/		");
		urls.add("	https://www.inboxhealth.com/		");
		urls.add("	http://imscc.com/		");
		urls.add("	https://prognocis.com/		");
		urls.add("	http://medicalintelligence.com		");
		urls.add("	https://astiahealth.com/		");
		urls.add("	http://www.blueskytelehealth.com		");
		urls.add("	https://mavens.com		");
		urls.add("	http://www.mhin.org		");
		urls.add("	http://www.healthcombix.com		");
		urls.add("	http://www.gweepi.com		");
		urls.add("	http://www.rightpatient.com		");
		urls.add("	http://www.conexem.com		");
		urls.add("	https://cliniconex.com/		");
		urls.add("	http://www.dhpionline.com		");
		urls.add("	https://www.meddatalink.com/index.html		");
		urls.add("	https://www.supplycopia.com:443/		");
		urls.add("	http://www.p2link.net		");
		urls.add("	https://www.archwayhealth.com/		");
		urls.add("	http://www.ehealthglobal.com		");
		urls.add("	http://www.inliant.com		");
		urls.add("	http://www.nextstepsolutionsinc.com		");
		urls.add("	http://www.pharmspective.com		");
		urls.add("	http://xcitehealth.com/		");
		urls.add("	http://www.evermind.us		");
		urls.add("	http://www.horizonhealthware.com		");
		urls.add("	http://www.clinicmaster.com		");
		urls.add("	http://www.rimedio.com		");
		urls.add("	http://www.positionhealth.co		");
		urls.add("	http://www.patientconnecter.com		");
		urls.add("	http://mednetinc.com		");
		urls.add("	https://axiscaresales.com/		");
		urls.add("	http://www.g8wayhealthpayments.com		");
		urls.add("	http://www.rcadia.com		");
		urls.add("	http://www.kpnhealth.com		");
		urls.add("	https://www.t-res.net//		");
		urls.add("	http://www.telemed2020.com		");
		urls.add("	https://www.apollopracticemanagement.com/		");
		urls.add("	http://www.intouchemr.com		");
		urls.add("	http://www.iggbonow.com		");
		urls.add("	http://dscopesystems.com		");
		urls.add("	http://www.c3healthcarerx.com		");
		urls.add("	https://www.saviicare.com/		");
		urls.add("	http://ondemandhomecare.com		");
		urls.add("	http://www.TimelessMedical.com		");
		urls.add("	http://www.aprendasystems.com		");
		urls.add("	http://www.patienttrak.net		");
		urls.add("	http://www.radekal.com		");
		urls.add("	https://doxy.me/		");
		urls.add("	http://intake.io		");
		urls.add("	https://comprendo.com/		");
		urls.add("	http://www.MedRevComplete.com		");
		urls.add("	http://mclinicaltechnology.com		");
		urls.add("	http://www.doxcity.com/		");
		urls.add("	http://lynchpin.io		");
		urls.add("	http://www.ebsco.com/		");
		urls.add("	https://www.marzet.com		");
		urls.add("	http://wltsoftware.com/		");
		urls.add("	https://www.healthnetconnect.com/		");
		urls.add("	http://www.practicestudio.net/linkedin		");
		urls.add("	http://www.vevanto.com		");
		urls.add("	http://www.PTLive.me		");
		urls.add("	http://www.medford.md		");
		urls.add("	http://www.quiredata.com		");
		urls.add("	www.cansurround.com		");
		urls.add("	http://agnityglobal.com/		");
		urls.add("	https://tag.bio/		");
		urls.add("	https://www.trainer-rx.com/		");
		urls.add("	https://www.factor-14.com/		");
		urls.add("	https://www.weconnectrecovery.com/		");
		urls.add("	http://www.healthsight.com		");
		urls.add("	http://www.kangaroohealth.com		");
		urls.add("	https://orihealthcare.com		");
		urls.add("	https://upfronthealthcare.com/		");
		urls.add("	http://www.merit.ai		");
		urls.add("	http://body1.com		");
		urls.add("	https://samepagehealth.com/		");
		urls.add("	http://www.infieldhealth.com		");
		urls.add("	nexjhealth.com		");
		urls.add("	https://www.nableivf.com/		");
		urls.add("	https://www.edaris.com/		");
		urls.add("	https://convergentimaging.com/		");
		urls.add("	https://coinhealth.io/		");
		urls.add("	dothealth.ca		");
		urls.add("	http://www.xeniohealth.com		");
		urls.add("	rideroundtrip.com		");
		urls.add("	https://www.quartzclinical.com/		");
		urls.add("	https://www.pacemate.com/		");
		urls.add("	http://www.lifecyclehealth.com		");
		urls.add("	https://teleonhealth.com/		");
		urls.add("	https://eyecareleaders.com/		");
		urls.add("	https://www.cubex.com		");
		urls.add("	www.ahsrcm.com		");
		urls.add("	www.medtechsolutions.com		");
		urls.add("	http://www.startyouruprise.com/		");
		urls.add("	http://www.al-cloudcare.com		");
		urls.add("	https://aretehs.com/		");
		urls.add("	http://www.assessmentpsychology.com		");
		urls.add("	http://www.open-payments.com		");
		urls.add("	https://www.baltimoremedical.jobs/		");
		urls.add("	https://www.bp-solutions.net/		");
		urls.add("	https://carepaths.com/		");
		urls.add("	https://www.care360.com/		");
		urls.add("	https://www.drvisit.com/		");
		urls.add("	https://www.experiencedentistry.com/		");
		urls.add("	https://www.hipaatraining.com/		");
		urls.add("	https://www.housecall.healthcare/		");
		urls.add("	https://www.idahomedical.jobs/		");
		urls.add("	https://www.ltcquest.com/		");
		urls.add("	https://www.lungview.com/		");
		urls.add("	https://www.michiganmedical.jobs/		");
		urls.add("	https://mtelehealth.com/		");
		urls.add("	https://www.nevadamedical.jobs/		");
		urls.add("	https://www.omicure.com/		");
		urls.add("	https://www.perfectcare.com/		");
		urls.add("	http://www.periopal.com		");
		urls.add("	https://www.physiciansignout.com/		");
		urls.add("	http://www.rabbithealthcare.com		");
		urls.add("	https://www.riversoft.net/		");
		urls.add("	https://www.softwaremotif.com/		");
		urls.add("	https://www.symbyos.com/		");
		urls.add("	http://www.synaphealth.com		");
		urls.add("	https://www.telemynd.com/		");
		urls.add("	http://www.tgisoftware.com		");
		urls.add("	http://www.thephysicianschoicehealthcare.com		");
		urls.add("	http://www.xms.com		");
		urls.add("	mednition.com		");
		urls.add("	https://swyftops.com/		");
		urls.add("	https://www.behavecare.us		");
		urls.add("	https://www.healthcubed.com		");
		urls.add("	http://www.invisalertsolutions.com		");
		urls.add("	https://www.care.ly		");
		urls.add("	https://www.heno.io		");
		urls.add("	https://www.bttcorp.com		");
		urls.add("	https://www.ardvrktech.com		");
		urls.add("	https://antibioticadjuvant.com/		");
		urls.add("	https://www.hyrmed.com		");
		urls.add("	https://www.ride-health.com		");
		urls.add("	https://www.intelehealth.org		");
		urls.add("	https://www.dentem.co		");
		urls.add("	https://kinometrix.com		");
		urls.add("	https://www.ristcall.com		");
		urls.add("	http://www.ekareinc.com		");
		urls.add("	https://quickrcare.com		");
		urls.add("	http://www.lifewallet.co		");
		urls.add("	https://www.medcomplianceiq.com		");
		urls.add("	https://guidingtechnologies.com/		");
		urls.add("	https://www.tpshealth.com		");
		urls.add("	http://www.futurelife.us		");
		urls.add("	http://www.hilabs.com		");
		urls.add("	https://www.orthoforge.com		");
		urls.add("	https://celerihealth.com:443/		");
		urls.add("	https://www.murj.com		");
		urls.add("	https://winterlightlabs.com/		");
		urls.add("	https://www.giblib.com		");
		urls.add("	https://www.sentinel.healthcare		");
		urls.add("	https://www.knowtions.com		");
		urls.add("	https://dearhealth.com/		");
		urls.add("	https://www.fallcall.com		");
		urls.add("	https://www.adaptiiv.com		");
		urls.add("	https://www.pillsy.com		");
		urls.add("	http://www.curvhealth.com/		");
		urls.add("	https://www.notesfirst.com		");
		urls.add("	http://www.gobiquity.com		");
		urls.add("	https://luminaremed.com		");
		urls.add("	https://www.legwork.com		");
		urls.add("	https://www.torchlight.care		");
		urls.add("	https://www.nightingale.app		");
		urls.add("	https://www.docbot.co		");
		urls.add("	https://www.cortexhc.com		");
		urls.add("	https://www.sharkdreams.co		");
		urls.add("	https://curogram.com		");
		urls.add("	http://echo-metrix.com/		");
		urls.add("	https://getversus.com/		");
		urls.add("	https://www.owlinsights.com		");
		urls.add("	https://www.syllable.ai		");
		urls.add("	http://abpathfinder.com		");
		urls.add("	http://medrunner.ca		");
		urls.add("	http://www.vyrty.com		");
		urls.add("	https://www.formathealth.com		");
		urls.add("	https://www.painqx.com		");
		urls.add("	http://www.friendlycares.com		");
		urls.add("	http://recovrinc.com/		");
		urls.add("	https://www.birdhousehq.com		");
		urls.add("	http://www.sarvint.com		");
		urls.add("	https://www.chronometriq.com/en/		");
		urls.add("	http://matrix-analytics.com/		");
		urls.add("	https://www.harmonimd.com		");
		urls.add("	https://blockitnow.com		");
		urls.add("	https://www.teamlinks.com		");
		urls.add("	https://aprihealth.com/		");
		urls.add("	https://www.oncobox.com		");
		urls.add("	https://www.siteofcare.com		");
		urls.add("	https://www.wellbrain.io		");
		urls.add("	https://moxytech.net/		");
		urls.add("	https://www.getelva.com/		");
		urls.add("	https://www.healthlinkages.com		");
		urls.add("	https://cht-inc.com/		");
		urls.add("	https://www.docbuddy.com		");
		urls.add("	https://tcisoftware.com/		");
		urls.add("	http://www.tula-health.com		");
		urls.add("	http://www.obaahealth.com		");
		urls.add("	https://www.baysil.com		");
		urls.add("	https://remindtrac.com/		");
		urls.add("	http://www.physiciansoftwaresystems.com		");
		urls.add("	http://www.qvidity.com		");
		urls.add("	https://www.ameri-pharma.com		");
		urls.add("	http://www.tellithealth.com		");
		urls.add("	https://www.liine.com		");
		urls.add("	https://www.totaljointpro.com		");
		urls.add("	multimodalhealth.com		");
		urls.add("	https://www.healthfully.io/		");
		urls.add("	http://www.vitaphone.de/en		");
		urls.add("	http://www.experior.com/		");
		urls.add("	tvrc.com		");
		urls.add("	https://webaba.com/		");
		urls.add("	https://www.emshealthcaresolutions.com/about/		");
		urls.add("	https://www.rldatix.com/en-nam/		");
		urls.add("	http://iberical.com/en		");
		urls.add("	https://www.curatio.me/		");
		urls.add("	https://myorlink.com/		");
		urls.add("	https://carewell.io/		");
		urls.add("	https://www.caresignal.health/		");
		urls.add("	https://neoteric.io/		");
		urls.add("	https://nikohealth.com/		");
		urls.add("	http://www.bennyhealth.com		");
		urls.add("	https://www.metadigital.tech/		");
		urls.add("	https://www.exdionrcm.com		");
		urls.add("	https://www.modelvitals.com		");
		urls.add("	https://www.prospection.com		");
		urls.add("	https://www.generationse.com		");
		urls.add("	http://itsguardian.com		");
		urls.add("	https://www.siramedical.com		");
		urls.add("	https://www.pocussystems.com		");
		urls.add("	https://www.starapps.co		");
		urls.add("	https://www.theweallife.com		");
		urls.add("	https://www.lyflynks.com		");
		urls.add("	http://loop.tech		");
		urls.add("	https://www.aneltohealth.com		");
		urls.add("	http://www.meetvela.com		");
		urls.add("	https://sommlhealth.com/		");
		urls.add("	https://www.drrounds.com		");
		urls.add("	https://www.proventushealth.com		");
		urls.add("	https://www.vemrinc.com		");
		urls.add("	https://www.knackglobal.com		");
		urls.add("	https://medvertex.com/		");
		urls.add("	https://remmanager.com/		");
		urls.add("	https://askmarvee.com/		");
		urls.add("	https://www.kinto.care		");
		urls.add("	https://www.twistintegrations.com		");
		urls.add("	https://medicalcyberworlds.com/		");
		urls.add("	https://tsquare.io		");
		urls.add("	http://www.micropaceep.com		");
		urls.add("	http://www.urgichart.com		");
		urls.add("	https://www.caretrax.net		");
		urls.add("	https://www.ayratelecare.com		");
		urls.add("	https://claimjudge.com/		");
		urls.add("	https://celearningsystems.com/		");
		urls.add("	https://www.appointmaster.com		");
		urls.add("	https://www.or-tracker.com		");
		urls.add("	https://www.orthobistro.com		");
		urls.add("	https://www.mymobilehc.com		");
		urls.add("	https://advancedcare.com		");
		urls.add("	https://www.pulsehealth.tech		");
		urls.add("	https://woundassure.com/		");
		urls.add("	https://dr-b.ca/		");
		urls.add("	https://www.carenodes.com		");
		urls.add("	https://www.xerusmedical.com		");
		urls.add("	http://nubmed.com.mx/		");
		urls.add("	https://surff.co		");
		urls.add("	http://www.scriptorsoftware.com		");
		urls.add("	https://journeyhealthlabs.com/		");
		urls.add("	https://gialliance.com/		");
		urls.add("	https://www.chorus.cloud		");
		urls.add("	https://www.orflow.us		");
		urls.add("	https://www.5startelemed.com		");
		urls.add("	https://dyadmed.com/		");
		urls.add("	https://www.curisdata.com		");
		urls.add("	https://www.valisbioscience.com		");
		urls.add("	http://www.doctustech.com		");
		urls.add("	http://carex.tech		");
		urls.add("	https://www.epitel.com		");
		urls.add("	https://www.talkpathlive.com		");
		urls.add("	https://tqintelligence.com/		");
		urls.add("	https://neolytix.com/		");
		urls.add("	http://innovatehealth.tech/		");
		urls.add("	https://telemedic.top/		");
		urls.add("	https://www.all4life.ai		");
		urls.add("	https://www.electronic-health-information-system.ca		");
		urls.add("	http://www.keacare.com		");
		urls.add("	https://www.everyonesacaregiver.com		");
		urls.add("	https://continuud.com/		");
		urls.add("	http://int.public.idoctus.com/		");
		urls.add("	https://www.formdox.com		");
		urls.add("	https://www.meta.app		");
		urls.add("	https://medlearn.app		");
		urls.add("	https://www.plexusmed.com		");
		urls.add("	https://insighealth.com/		");
		urls.add("	http://www.inscenta.com		");
		urls.add("	https://www.objectivepathology.com		");
		urls.add("	https://voiceboxmd.com/		");
		urls.add("	https://www.maxpatient.com		");
		urls.add("	http://www.medicalrmsoftware.com		");
		urls.add("	https://www.wize.ai		");
		urls.add("	https://cord.health/		");
		urls.add("	https://safespace.health		");
		urls.add("	https://easymanagehealth.com/		");
		urls.add("	https://telelytics.io/		");
		urls.add("	https://www.privehealth.ca		");
		urls.add("	https://www.joinbloomcare.ca		");
		urls.add("	http://person.clinic/		");
		urls.add("	https://www.quatrishealthco.com		");
		urls.add("	https://www.agylesolutions.com		");
		urls.add("	https://pages.ikona.health/main		");
		urls.add("	http://chronicare.com		");
		urls.add("	https://www.scrubbedapp.com		");
		urls.add("	http://www.statech.co		");
		urls.add("	https://bluebox.care/		");
		urls.add("	https://www.digitalhealthsolutionsllc.com		");
		urls.add("	https://www.emeraldinno.com		");
		urls.add("	http://www.connectedcare.io		");
		urls.add("	https://www.lyssn.io		");
		urls.add("	https://avocare.ca/		");
		urls.add("	https://www.px6medicalsystems.com		");
		urls.add("	https://serinushealth.com/		");
		urls.add("	http://www.simopsolutions.io		");
		urls.add("	https://www.carecrew.ca		");
		urls.add("	https://www.rmdy.io		");
		urls.add("	https://www.apotheka.co		");
		urls.add("	https://medtrics.io/		");
		urls.add("	https://www.xr.health		");
		urls.add("	https://www.coral.io		");
		urls.add("	https://www.kalibrateblockchain.io		");
		urls.add("	http://medpather.com		");
		urls.add("	https://www.medicinets.com		");
		urls.add("	https://www.vitinitiative.com		");
		urls.add("	https://physician-data.com/		");
		urls.add("	https://chiroup.com/		");
		urls.add("	http://www.seniorlivingcrm.com		");
		urls.add("	https://www.provenbackup.com		");
		urls.add("	https://www.genixtec.com		");
		urls.add("	https://www.realtimephysician.com		");
		urls.add("	https://www.zeusdatasolutions.com		");
		urls.add("	https://althea.care/		");
		urls.add("	https://www.mooremartinimedical.com		");
		urls.add("	http://activeos.com/		");
		urls.add("	https://www.ischemaview.com		");
		urls.add("	https://acemapp.org/		");
		urls.add("	https://www.oncopower.org		");
		urls.add("	https://www.medicalmine.com		");
		urls.add("	https://www.konvergent.io		");
		urls.add("	https://www.seriouserp.com		");
		urls.add("	https://www.zolacrm.com		");
		urls.add("	http://www.singlestep.io		");
		urls.add("	https://www.invibe.co		");
		urls.add("	http://coordinatedcarehn.com/		");
		urls.add("	https://www.decisiondiagnostics.co		");
		urls.add("	https://cohesic.com/		");
		urls.add("	http://inlightened.co/		");
		urls.add("	https://m.care/		");
		urls.add("	http://oblix.healthcare		");
		urls.add("	http://www.telecuris.com		");
		urls.add("	https://www.reputation-health.com		");
		urls.add("	https://www.actualizetherapy.com		");
		urls.add("	http://www.health-seeker.com		");
		urls.add("	https://www.corralsolutions.com		");
		urls.add("	https://www.echarthealthcare.com		");
		urls.add("	https://www.medivis.co		");
		urls.add("	http://www.tabeeb.org		");
		urls.add("	http://www.voxelhealthcare.com		");
		urls.add("	https://www.blumtelehealth.com		");
		urls.add("	https://truereply.com/		");
		urls.add("	https://raivenhealth.com/		");
		urls.add("	http://www.possibilitiesforchange.com		");
		urls.add("	https://www.zip-doc.com		");
		urls.add("	https://www.ltcmis.net		");
		urls.add("	https://www.listenmd.com		");
		urls.add("	https://eyecarelive.com/		");
		urls.add("	https://www.takpoints.com		");
		urls.add("	http://www.vennar.com		");
		urls.add("	http://www.clickpatient.com		");
		urls.add("	https://www.notifius.com		");
		urls.add("	https://mdvision.net		");
		urls.add("	http://www.doctorsbestmarketing.com		");
		urls.add("	http://www.asm-inc.com		");
		urls.add("	http://lumamed.net		");
		urls.add("	https://reemohealth.com/		");
		urls.add("	https://www.aestheticrecord.com		");
		urls.add("	http://www.towersys.com		");
		urls.add("	https://rndsapp.com/		");
		urls.add("	https://pulseradiology.com/		");
		urls.add("	https://www.mdsystems.net		");
		urls.add("	http://projectivesoftware.com		");
		urls.add("	https://www.incrediblehq.com		");
		urls.add("	https://grythealth.com/		");
		urls.add("	https://www.myndvr.com		");
		urls.add("	https://codeblueapp.com/		");
		urls.add("	https://www.queuelogix.com		");
		urls.add("	http://www.worldintermed.com		");
		urls.add("	https://www.pharm3r.com		");
		urls.add("	https://www.hugophr.com		");
		urls.add("	https://www.torchinsight.com		");
		urls.add("	http://www.tricubics.com		");
		urls.add("	https://ceremetrix.io/		");
		urls.add("	https://www.interactivemetronome.com		");
		urls.add("	https://skiniq.co		");
		urls.add("	http://www.patient-click.com		");
		urls.add("	https://medicalprofessor.net/		");
		urls.add("	https://proovn.com/index.cfm		");
		urls.add("	https://www.lightningmd.com		");
		urls.add("	https://www.dentalemr.com		");
		urls.add("	https://www.msbiotics.com		");
		urls.add("	http://www.elahealth.com		");
		urls.add("	http://www.portal724.ca		");
		urls.add("	https://pteverywhere.com/		");
		urls.add("	https://www.orchestraone.com		");
		urls.add("	http://clinicalha.com/		");
		urls.add("	https://stiinnovations.com/		");
		urls.add("	http://angarus.io/		");
		urls.add("	https://www.hcxpinc.com		");
		urls.add("	http://www.clearpathderm.com		");
		urls.add("	https://www.medphotomanager.com		");
		urls.add("	https://www.physicianattendant.com		");
		urls.add("	https://eyecarepd.com/		");
		urls.add("	https://practicebetter.io/		");
		urls.add("	http://nyx-med.com/		");
		urls.add("	https://clinicanywhere.com/		");
		urls.add("	https://www.agentplus.ca		");
		urls.add("	https://fited.co/		");
		urls.add("	https://www.healpoint.io		");
		urls.add("	http://www.cureativecontent.com		");
		urls.add("	https://www.logik.net		");
		urls.add("	https://www.vistalifesciences.com		");
		urls.add("	https://medably.com		");
		urls.add("	http://maxmed.io/		");
		urls.add("	https://www.eye-iq.com		");
		urls.add("	https://www.med.me/en/		");
		urls.add("	http://www.champaignimaging.com		");
		urls.add("	http://www.snapptec.com/		");
		urls.add("	http://4d-imaging.com/		");
		urls.add("	https://www.gomedhaul.com		");
		urls.add("	https://spectrum.md		");
		urls.add("	http://medeligo.com/		");
		urls.add("	https://www.togglehealth.com		");
		urls.add("	https://www.chirpyhire.com		");
		urls.add("	https://www.quantinsights.com		");
		urls.add("	https://healable.com/		");
		urls.add("	http://engageder.com		");
		urls.add("	https://www.trim-ai.com		");
		urls.add("	https://www.meliorix.com		");
		urls.add("	https://www.inrecovery.org		");
		urls.add("	https://www.xybionhealth.com		");
		urls.add("	https://mystreamd.com		");
		urls.add("	https://www.myndplan.com		");
		urls.add("	http://www.incedo.us		");
		urls.add("	http://www.epsilonimaging.com		");
		urls.add("	https://www.parrotsoftware.com		");
		urls.add("	http://www.elarahealthcare.com		");
		urls.add("	http://www.ddsgeeks.com		");
		urls.add("	https://www.neurolex.ai		");
		urls.add("	https://keeponmovin.com/		");
		urls.add("	https://www.limbix.com		");
		urls.add("	https://www.wisersys.com		");
		urls.add("	https://www.zensupplies.com		");
		urls.add("	https://www.oplogix.com		");
		urls.add("	https://telehealth.org/		");
		urls.add("	https://shadewave.com/		");
		urls.add("	https://www.pandaperio.com		");
		urls.add("	https://survivorplan.io/		");
		urls.add("	https://www.inventrix.us.com		");
		urls.add("	https://www.labstar.com		");
		urls.add("	https://rapiddosimetry.com		");
		urls.add("	http://prophitinsight.com		");
		urls.add("	http://www.vaultara.com		");
		urls.add("	http://www.arcosmedical.com		");
		urls.add("	https://xtractsolutions.com		");
		urls.add("	https://www.neuroscouting.com		");
		urls.add("	http://www.anatomyonline.com		");
		urls.add("	https://thebodyvr.com/		");
		urls.add("	http://organizerhope.com/		");
		urls.add("	http://www.experior.org		");
		urls.add("	https://www.glidian.com		");
		urls.add("	http://www.virtualphantoms.com		");
		urls.add("	http://www.atomicradiology.com		");
		urls.add("	http://www.profitmd.com		");
		urls.add("	https://avedis.io/		");
		urls.add("	http://v-medicus.com		");
		urls.add("	https://healthepractices.com/		");
		urls.add("	http://www.cbt4cbt.com		");
		urls.add("	https://www.curbsidemdlive.com		");
		urls.add("	https://greenlight.md/		");
		urls.add("	https://kinuu.com/		");
		urls.add("	http://www.med2lab.com		");
		urls.add("	http://www.aloha.me		");
		urls.add("	http://retinasvr.com		");
		urls.add("	https://www.backtable.com		");
		urls.add("	http://clearancy.co		");
		urls.add("	https://vitalogics.com		");
		urls.add("	https://www.versasoft.net		");
		urls.add("	https://www.thedoctorschannel.com		");
		urls.add("	https://www.chiro-billing.com/cgi-sys/suspendedpage.cgi		");
		urls.add("	http://peaque.net		");
		urls.add("	http://www.healthtechsoftware.com		");
		urls.add("	http://behavioralhealthcaresoftware.com		");
		urls.add("	http://casenetwork.com/		");
		urls.add("	http://airmed.io		");
		urls.add("	https://www.managingmds.com		");
		urls.add("	http://lightworkersstaffing.com/		");
		urls.add("	http://www.hudlhealth.com		");
		urls.add("	https://evolvemed.com		");
		urls.add("	https://www.axonvirtualhealth.com		");
		urls.add("	https://www.virtuallybetter.com		");
		urls.add("	https://careteamsolutions.com/		");
		urls.add("	https://www.patientplus.com		");
		urls.add("	https://www.ecosofthealth.com		");
		urls.add("	https://pathmedo.com/		");
		urls.add("	https://www.glyqa.com		");
		urls.add("	https://dentalrat.com/		");
		urls.add("	http://www.qclinics.com		");
		urls.add("	http://cmmhealthcare.com		");
		urls.add("	https://www.medtracc.com		");
		urls.add("	https://www.kelahealth.com		");
		urls.add("	http://www.kidshealthrecord.com		");
		urls.add("	https://www.somasens.com/		");
		urls.add("	https://www.mypurplefolder.com		");
		urls.add("	https://www.healthmaster.com		");
		urls.add("	http://www.medplus.com		");
		urls.add("	https://www.bewellmobile.com		");
		urls.add("	http://catmedis.com		");
		urls.add("	https://fluent.systems/		");
		urls.add("	https://www.mai.ai		");
		urls.add("	https://treatment.com/		");
		urls.add("	http://www.dentalexec.com		");
		urls.add("	https://caretime.us		");
		urls.add("	http://www.credit.healthcare		");
		urls.add("	https://www.visitrack.us		");
		urls.add("	http://outcomes.com		");
		urls.add("	http://www.allostatix.com		");
		urls.add("	https://www.vasantahealth.com		");
		urls.add("	https://wiseyak.com/		");
		urls.add("	http://zenxmed.com		");
		urls.add("	https://clinicw.co/		");
		urls.add("	http://www.backbeatmedical.com		");
		urls.add("	https://www.webchartnow.com		");
		urls.add("	https://www.listen.md		");
		urls.add("	https://etherapydocs.com		");
		urls.add("	https://quick-charts.com/		");
		urls.add("	https://www.genidsolutions.com		");
		urls.add("	http://www.debriefly.com		");
		urls.add("	https://repwatch.co/		");
		urls.add("	https://www.symptomedic.com		");
		urls.add("	http://www.care3.co		");
		urls.add("	http://www.imarssystems.com		");
		urls.add("	http://www.myphm.com		");
		urls.add("	http://www.us4hs.com		");
		urls.add("	http://careheroes.co		");
		urls.add("	https://www.rxpense.com		");
		urls.add("	https://www.psychpatient.com		");
		urls.add("	http://www.remind-tech.co		");
		urls.add("	http://www.reminder-rosie.com		");
		urls.add("	https://specimentrack.com/		");
		urls.add("	http://www.statimllc.com		");
		urls.add("	http://www.algosdata.com/		");
		urls.add("	http://compass-inc.com		");
		urls.add("	http://quiro.co		");
		urls.add("	http://www.dreamdiabetes.com		");
		urls.add("	https://www.medcircle.com		");
		urls.add("	http://amitycare.org		");
		urls.add("	http://contextsurgery.com		");
		urls.add("	https://sanersoftware.com/		");
		urls.add("	http://www.healthcrew.me		");
		urls.add("	http://www.inventurus.com		");
		urls.add("	http://www.nitropcr.com		");
		urls.add("	https://cloudfaceusa.com/		");
		urls.add("	https://www.finhealth.com		");
		urls.add("	https://www.tecsomed.com		");
		urls.add("	http://www.tihealthcare.com		");
		urls.add("	http://www.curatehealth.me		");
		urls.add("	https://www.mckessonspecialtyhealth.com		");
		urls.add("	http://www.careprogress.com		");
		urls.add("	http://virtualvisitsolutions.com		");
		urls.add("	http://www.simnext.com		");
		urls.add("	https://www.toltech.net		");
		urls.add("	https://www.simulaids.com		");
		urls.add("	https://aiocare.com/patient/		");
		urls.add("	http://www.theonhealth.com		");
		urls.add("	http://www.primewellness.com		");
		urls.add("	https://www.careguard.com		");
		urls.add("	https://www.getitanalytics.com		");
		urls.add("	http://www.serumagency.com		");
		urls.add("	http://carefacets.com		");
		urls.add("	http://caremaxbilling.com		");
		urls.add("	https://complete.md/		");
		urls.add("	http://systolik.com		");

		Iterator iterator= urls.iterator();
		while (iterator.hasNext()) {
			String urlLink= (String) iterator.next();
				
			count++;
			String content =null;
			Elements linkedInLink;
			try {

				Document document=Jsoup.connect(urlLink).followRedirects(true).timeout(100000).get();
				//System.out.println(count+")"+urlLink);

				/*
				 * String twitterPattern =
				 * "(http|https){0,1}:{0,1}://(www.)?(twitter.)[A-Za-z0-9-_./?=]{0,100}";
				 * Elements twitterLink= document.getElementsByAttributeValueContaining("href",
				 * "twitter.com");
				 * 
				 * if(!twitterLink.attr("href").isBlank()) {
				 * if(twitterLink.attr("href").matches(twitterPattern)) {
				 * System.out.println("Twitter link    ---> "+twitterLink.attr("href")); } }
				 * 
				 * String fbPattern =
				 * "(http|https){0,1}:{0,1}//(www.)?(facebook.){0,1}[A-Za-z0-9-_./?=]{0,100}";
				 * Elements fbLink= document.getElementsByAttributeValueContaining("href",
				 * "facebook.com/"); if(!fbLink.attr("href").isBlank()) {
				 * if(fbLink.attr("href").matches(fbPattern)) {
				 * System.out.println("facebook link    ---> "+fbLink.attr("href")); }
				 * 
				 * }
				 */
	            //Linkedin

				String linkedinPattern = "(http|https){0,1}:{0,1}//(www.)?(linkedin.)[a-z0-9!-/:-@\\[-`\\{-~]*";
				String linkedinPattern1="((linkedin.com/company/)|(linkedin.com/in/))";
				
					linkedInLink= document.getElementsByAttributeValueMatching("href", linkedinPattern1);
				
				if(!linkedInLink.attr("href").isEmpty())
				{
					if(linkedInLink.attr("href").matches(linkedinPattern))
					{	
						System.out.println(linkedInLink.attr("href"));
						content =linkedInLink.attr("href");
					}else
					{
						content="timing";
						System.out.println("timing");
					}
				}else {
					content="url not available";
					System.out.println("url not available");
				}
               
				/*
				 * //Youtube String youtubePattern =
				 * "(http|https){0,1}:{0,1}//(www.)?(youtube.com)(channel|user){0,1}[A-Za-z0-9-_./?=]{0,100}";
				 * Elements youtubLink= document.getElementsByAttributeValueContaining("href",
				 * "youtube.com"); if(!youtubLink.attr("href").isBlank()) {
				 * if(youtubLink.attr("href").matches(youtubePattern)) {
				 * System.out.println("Youtube Link     ---> "+youtubLink.attr("href")); }
				 * 
				 * }
				 * 
				 * //instagram String instaPattern =
				 * "(http|https){0,1}:{0,1}//(www.)?(instagram.)[A-Za-z0-9-_./?=]{0,100}";
				 * Elements instagramLink=
				 * document.getElementsByAttributeValueContaining("href", "instagram.com");
				 * if(!instagramLink.attr("href").isBlank()) {
				 * 
				 * if(instagramLink.attr("href").matches(instaPattern)) {
				 * System.out.println("Instagram Link   ---> "+instagramLink.attr("href")); }
				 * 
				 * }
				 */
				//System.out.println();
			}
			catch (Exception e) {
				content="url probleml";
	
			}
		       try (FileWriter writer = new FileWriter(
                       "C:\\Users\\oppeddamadthala\\Documents\\linkedin urls\\final__run.txt", true);
                       BufferedWriter bw = new BufferedWriter(writer)) {
		    	   
                   bw.write(content);
                   bw.write("\n");
		       }catch (Exception e) {
				//e.printStackTrace();
			}



                   
		}
	}
}


