package com.aldrich.softwaresuggest;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

public class Test {

	public static void main(String[] args) throws InterruptedException  {

		WebDriver companyPage=null;
		WebDriver chromeDriver = null;
		WebElement element=null;
		chromeDriver=setChromeDriver();
		if(chromeDriver!=null)
		{   
			List<String> url=new ArrayList<String>();
			url.add("	https://www.softwaresuggest.com/accounting-software	");
			url.add("	https://www.softwaresuggest.com/accounting-services	");
			url.add("	https://www.softwaresuggest.com/accounts-payable-software	");
			url.add("	https://www.softwaresuggest.com/accounts-receivable-software	");
			url.add("	https://www.softwaresuggest.com/aml-software	");
			url.add("	https://www.softwaresuggest.com/auto-dealer-accounting-software	");
			url.add("	https://www.softwaresuggest.com/bookkeeping-software	");
			url.add("	https://www.softwaresuggest.com/budgeting-software	");
			url.add("	https://www.softwaresuggest.com/call-accounting-software	");
			url.add("	https://www.softwaresuggest.com/cash-collection-software	");
			url.add("	https://www.softwaresuggest.com/church-accounting-software	");
			url.add("	https://www.softwaresuggest.com/fixed-asset-accounting-software	");
			url.add("	https://www.softwaresuggest.com/fund-accounting-software	");
			url.add("	https://www.softwaresuggest.com/gst-software	");
			url.add("	https://www.softwaresuggest.com/gst-rate-finder-software	");
			url.add("	https://www.softwaresuggest.com/gst-reconciliation-software	");
			url.add("	https://www.softwaresuggest.com/lease-accounting-software	");
			url.add("	https://www.softwaresuggest.com/online-accounting-software	");
			url.add("	https://www.softwaresuggest.com/small-business-accounting-software	");
			url.add("	https://www.softwaresuggest.com/trust-accounting-software	");
			url.add("	https://www.softwaresuggest.com/asset-management-software	");
			url.add("	https://www.softwaresuggest.com/cmdb-software	");
			url.add("	https://www.softwaresuggest.com/digital-asset-management-software	");
			url.add("	https://www.softwaresuggest.com/remote-asset-management-software	");
			url.add("	https://www.softwaresuggest.com/billing-invoicing-software	");
			url.add("	https://www.softwaresuggest.com/billing-provisioning-software	");
			url.add("	https://www.softwaresuggest.com/einvoicing-software	");
			url.add("	https://www.softwaresuggest.com/eway-bill-software	");
			url.add("	https://www.softwaresuggest.com/legal-billing-software	");
			url.add("	https://www.softwaresuggest.com/medical-billing-software	");
			url.add("	https://www.softwaresuggest.com/recurring-billing-software	");
			url.add("	https://www.softwaresuggest.com/restaurant-billing-software	");
			url.add("	https://www.softwaresuggest.com/subscription-billing-software	");
			url.add("	https://www.softwaresuggest.com/supermarket-billing-software	");
			url.add("	https://www.softwaresuggest.com/utility-billing-software	");
			url.add("	https://www.softwaresuggest.com/barcode-billing-software	");
			url.add("	https://www.softwaresuggest.com/business-intelligence-tools	");
			url.add("	https://www.softwaresuggest.com/business-plan-software	");
			url.add("	https://www.softwaresuggest.com/competitive-intelligence-software	");
			url.add("	https://www.softwaresuggest.com/conversational-ai-platform-software	");
			url.add("	https://www.softwaresuggest.com/digital-workplace-software	");
			url.add("	https://www.softwaresuggest.com/machine-learning-software	");
			url.add("	https://www.softwaresuggest.com/virtual-data-room-software	");
			url.add("	https://www.softwaresuggest.com/virtual-machine-software	");
			url.add("	https://www.softwaresuggest.com/virtual-tour-software	");
			url.add("	https://www.softwaresuggest.com/virtualization-software	");
			url.add("	https://www.softwaresuggest.com/virtual-reality-vr-software	");
			url.add("	https://www.softwaresuggest.com/big-data-software	");
			url.add("	https://www.softwaresuggest.com/artificial-intelligence-software	");
			url.add("	https://www.softwaresuggest.com/augmented-reality-software	");
			url.add("	https://www.softwaresuggest.com/simulation-software	");
			url.add("	https://www.softwaresuggest.com/collaboration-software	");
			url.add("	https://www.softwaresuggest.com/email-collaboration-tools	");
			url.add("	https://www.softwaresuggest.com/meeting-room-booking-software	");
			url.add("	https://www.softwaresuggest.com/presentation-software	");
			url.add("	https://www.softwaresuggest.com/board-management-software	");
			url.add("	https://www.softwaresuggest.com/board-meeting-software	");
			url.add("	https://www.softwaresuggest.com/knowledge-management-system	");
			url.add("	https://www.softwaresuggest.com/iwms-software	");
			url.add("	https://www.softwaresuggest.com/online-proofing-software	");
			url.add("	https://www.softwaresuggest.com/communication-conferencing-software	");
			url.add("	https://www.softwaresuggest.com/contact-center-software	");
			url.add("	https://www.softwaresuggest.com/contact-management-software	");
			url.add("	https://www.softwaresuggest.com/digital-voice-logging-software	");
			url.add("	https://www.softwaresuggest.com/intelligent-phone-system	");
			url.add("	https://www.softwaresuggest.com/internal-communication-software	");
			url.add("	https://www.softwaresuggest.com/office-phone-system	");
			url.add("	https://www.softwaresuggest.com/predictive-dialer-software	");
			url.add("	https://www.softwaresuggest.com/softphone-software	");
			url.add("	https://www.softwaresuggest.com/speech-recognition-software	");
			url.add("	https://www.softwaresuggest.com/team-communication-software	");
			url.add("	https://www.softwaresuggest.com/telecommunication-software	");
			url.add("	https://www.softwaresuggest.com/unified-communication-system	");
			url.add("	https://www.softwaresuggest.com/voip-software	");
			url.add("	https://www.softwaresuggest.com/auto-dialer-software	");
			url.add("	https://www.softwaresuggest.com/acd-software	");
			url.add("	https://www.softwaresuggest.com/business-phone-system	");
			url.add("	https://www.softwaresuggest.com/call-center-software	");
			url.add("	https://www.softwaresuggest.com/call-tracking-software	");
			url.add("	https://www.softwaresuggest.com/cloud-communication-platform-software	");
			url.add("	https://www.softwaresuggest.com/cloud-telephony-ivrs-software	");
			url.add("	https://www.softwaresuggest.com/webinar-software	");
			url.add("	https://www.softwaresuggest.com/tele-marketing-software	");
			url.add("	https://www.softwaresuggest.com/video-conferencing-software	");
			url.add("	https://www.softwaresuggest.com/app-development-software	");
			url.add("	https://www.softwaresuggest.com/application-performance-management-tools	");
			url.add("	https://www.softwaresuggest.com/archiving-software	");
			url.add("	https://www.softwaresuggest.com/automation-testing-tools	");
			url.add("	https://www.softwaresuggest.com/bug-software	");
			url.add("	https://www.softwaresuggest.com/bug-fixing-software	");
			url.add("	https://www.softwaresuggest.com/cloud-computing-services	");
			url.add("	https://www.softwaresuggest.com/cloud-pbx-system	");
			url.add("	https://www.softwaresuggest.com/cloud-storage-software	");
			url.add("	https://www.softwaresuggest.com/computer-monitoring-software	");
			url.add("	https://www.softwaresuggest.com/computer-repair-shop-software	");
			url.add("	https://www.softwaresuggest.com/computer-security-software	");
			url.add("	https://www.softwaresuggest.com/cyber-security-software	");
			url.add("	https://www.softwaresuggest.com/devops-tools	");
			url.add("	https://www.softwaresuggest.com/digital-adoption-platform-software	");
			url.add("	https://www.softwaresuggest.com/encryption-software	");
			url.add("	https://www.softwaresuggest.com/endpoint-security-software	");
			url.add("	https://www.softwaresuggest.com/firewall-software	");
			url.add("	https://www.softwaresuggest.com/game-development-software	");
			url.add("	https://www.softwaresuggest.com/gamification-software	");
			url.add("	https://www.softwaresuggest.com/integration-software	");
			url.add("	https://www.softwaresuggest.com/internet-security-software	");
			url.add("	https://www.softwaresuggest.com/intranet-software	");
			url.add("	https://www.softwaresuggest.com/iot-software	");
			url.add("	https://www.softwaresuggest.com/ipad-kiosk-software	");
			url.add("	https://www.softwaresuggest.com/java-cms-software	");
			url.add("	https://www.softwaresuggest.com/kiosk-software	");
			url.add("	https://www.softwaresuggest.com/microsoft-partner	");
			url.add("	https://www.softwaresuggest.com/mobile-analytics-software	");
			url.add("	https://www.softwaresuggest.com/mobile-app-development-services	");
			url.add("	https://www.softwaresuggest.com/mobile-banking-software	");
			url.add("	https://www.softwaresuggest.com/mobile-credit-card-processing-software	");
			url.add("	https://www.softwaresuggest.com/mobile-data-recovery-software	");
			url.add("	https://www.softwaresuggest.com/mobile-data-recovery-software	");
			url.add("	https://www.softwaresuggest.com/mobile-device-management-software	");
			url.add("	https://www.softwaresuggest.com/patch-management-software	");
			url.add("	https://www.softwaresuggest.com/php-scripts	");
			url.add("	https://www.softwaresuggest.com/programming-software	");
			url.add("	https://www.softwaresuggest.com/remote-desktop-software	");
			url.add("	https://www.softwaresuggest.com/remote-support-software	");
			url.add("	https://www.softwaresuggest.com/robotic-process-automation-software	");
			url.add("	https://www.softwaresuggest.com/server-monitoring-tools	");
			url.add("	https://www.softwaresuggest.com/software-testing-tools	");
			url.add("	https://www.softwaresuggest.com/source-code-management-software	");
			url.add("	https://www.softwaresuggest.com/system-software	");
			url.add("	https://www.softwaresuggest.com/visual-search-software	");
			url.add("	https://www.softwaresuggest.com/web-hosting-services	");
			url.add("	https://www.softwaresuggest.com/ab-testing-software	");
			url.add("	https://www.softwaresuggest.com/anti-spam-software	");
			url.add("	https://www.softwaresuggest.com/antivirus-software	");
			url.add("	https://www.softwaresuggest.com/api-management-software	");
			url.add("	https://www.softwaresuggest.com/app-builder-software	");
			url.add("	https://www.softwaresuggest.com/load-balancing-software	");
			url.add("	https://www.softwaresuggest.com/version-control-system	");
			url.add("	https://www.softwaresuggest.com/wireframe-tools	");
			url.add("	https://www.softwaresuggest.com/alm-software	");
			url.add("	https://www.softwaresuggest.com/android-recovery-software	");
			url.add("	https://www.softwaresuggest.com/ide-software	");
			url.add("	https://www.softwaresuggest.com/construction-management-software	");
			url.add("	https://www.softwaresuggest.com/construction-scheduling-software	");
			url.add("	https://www.softwaresuggest.com/punch-list-software	");
			url.add("	https://www.softwaresuggest.com/residential-construction-estimating-software	");
			url.add("	https://www.softwaresuggest.com/roofing-software	");
			url.add("	https://www.softwaresuggest.com/takeoff-software	");
			url.add("	https://www.softwaresuggest.com/textile-industry-software	");
			url.add("	https://www.softwaresuggest.com/architecture-software	");
			url.add("	https://www.softwaresuggest.com/construction-bidding-software	");
			url.add("	https://www.softwaresuggest.com/construction-crm-software	");
			url.add("	https://www.softwaresuggest.com/content-management-software	");
			url.add("	https://www.softwaresuggest.com/content-writing-services	");
			url.add("	https://www.softwaresuggest.com/course-authoring-software	");
			url.add("	https://www.softwaresuggest.com/ocr-software	");
			url.add("	https://www.softwaresuggest.com/print-estimating-software	");
			url.add("	https://www.softwaresuggest.com/proofreading-software	");
			url.add("	https://www.softwaresuggest.com/translation-management-software	");
			url.add("	https://www.softwaresuggest.com/blog-software	");
			url.add("	https://www.softwaresuggest.com/ecm-enterprise-content-management-software	");
			url.add("	https://www.softwaresuggest.com/customer-support-software	");
			url.add("	https://www.softwaresuggest.com/help-desk-software	");
			url.add("	https://www.softwaresuggest.com/live-chat-software	");
			url.add("	https://www.softwaresuggest.com/complaint-management-system	");
			url.add("	https://www.softwaresuggest.com/customer-engagement-software	");
			url.add("	https://www.softwaresuggest.com/customer-service-software	");
			url.add("	https://www.softwaresuggest.com/nps-software	");
			url.add("	https://www.softwaresuggest.com/crm-software	");
			url.add("	https://www.softwaresuggest.com/customer-advocacy-software	");
			url.add("	https://www.softwaresuggest.com/customer-data-platform-software	");
			url.add("	https://www.softwaresuggest.com/customer-database-software	");
			url.add("	https://www.softwaresuggest.com/customer-experience-management-software	");
			url.add("	https://www.softwaresuggest.com/customer-feedback-software	");
			url.add("	https://www.softwaresuggest.com/customer-journey-mapping-software	");
			url.add("	https://www.softwaresuggest.com/customer-loyalty-management-software	");
			url.add("	https://www.softwaresuggest.com/customer-reference-management-software	");
			url.add("	https://www.softwaresuggest.com/customer-success-software	");
			url.add("	https://www.softwaresuggest.com/inside-sales-software	");
			url.add("	https://www.softwaresuggest.com/online-crm-software	");
			url.add("	https://www.softwaresuggest.com/small-business-loyalty-programs-software	");
			url.add("	https://www.softwaresuggest.com/social-crm-software	");
			url.add("	https://www.softwaresuggest.com/after-sales-service-management-software	");
			url.add("	https://www.softwaresuggest.com/review-management-software	");
			url.add("	https://www.softwaresuggest.com/data-management-software	");
			url.add("	https://www.softwaresuggest.com/data-mining-software	");
			url.add("	https://www.softwaresuggest.com/data-quality-software	");
			url.add("	https://www.softwaresuggest.com/data-recovery-software	");
			url.add("	https://www.softwaresuggest.com/data-visualization-tools	");
			url.add("	https://www.softwaresuggest.com/data-warehouse-software	");
			url.add("	https://www.softwaresuggest.com/database-management-system	");
			url.add("	https://www.softwaresuggest.com/disk-imaging-software	");
			url.add("	https://www.softwaresuggest.com/edi-software	");
			url.add("	https://www.softwaresuggest.com/electronic-data-capture-software	");
			url.add("	https://www.softwaresuggest.com/etl-software	");
			url.add("	https://www.softwaresuggest.com/file-recovery-software	");
			url.add("	https://www.softwaresuggest.com/file-sharing-software	");
			url.add("	https://www.softwaresuggest.com/file-sync-software	");
			url.add("	https://www.softwaresuggest.com/gdpr-compliance-software	");
			url.add("	https://www.softwaresuggest.com/hard-drive-recovery-software	");
			url.add("	https://www.softwaresuggest.com/mapping-software	");
			url.add("	https://www.softwaresuggest.com/pim-software	");
			url.add("	https://www.softwaresuggest.com/privileged-access-management-software	");
			url.add("	https://www.softwaresuggest.com/product-data-management-software	");
			url.add("	https://www.softwaresuggest.com/spreadsheet-software	");
			url.add("	https://www.softwaresuggest.com/text-mining-software	");
			url.add("	https://www.softwaresuggest.com/web-to-print-software	");
			url.add("	https://www.softwaresuggest.com/data-analysis-software	");
			url.add("	https://www.softwaresuggest.com/data-analysis-software	");
			url.add("	https://www.softwaresuggest.com/data-discovery-tools	");
			url.add("	https://www.softwaresuggest.com/data-extraction-software	");
			url.add("	https://www.softwaresuggest.com/data-governance-tools	");
			url.add("	https://www.softwaresuggest.com/data-loss-prevention-software	");
			url.add("	https://www.softwaresuggest.com/backup-software	");
			url.add("	https://www.softwaresuggest.com/reporting-tools	");
			url.add("	https://www.softwaresuggest.com/statistical-analysis-software	");
			url.add("	https://www.softwaresuggest.com/data-entry-software	");
			url.add("	https://www.softwaresuggest.com/heatmap-software	");
			url.add("	https://www.softwaresuggest.com/sharepoint-migration-tools	");
			url.add("	https://www.softwaresuggest.com/photo-recovery-software	");
			url.add("	https://www.softwaresuggest.com/document-management-software	");
			url.add("	https://www.softwaresuggest.com/document-tracking-system	");
			url.add("	https://www.softwaresuggest.com/document-version-control-software	");
			url.add("	https://www.softwaresuggest.com/pdf-software	");
			url.add("	https://www.softwaresuggest.com/document-generation-tools	");
			url.add("	https://www.softwaresuggest.com/digital-signature-software	");
			url.add("	https://www.softwaresuggest.com/e-signature-software	");
			url.add("	https://www.softwaresuggest.com/distribution-management-software	");
			url.add("	https://www.softwaresuggest.com/vendors-management-software	");
			url.add("	https://www.softwaresuggest.com/wholesale-distribution-software	");
			url.add("	https://www.softwaresuggest.com/dealer-distributor-management-software	");
			url.add("	https://www.softwaresuggest.com/requirements-management-software	");
			url.add("	https://www.softwaresuggest.com/franchise-management-software	");
			url.add("	https://www.softwaresuggest.com/school-management-software	");
			url.add("	https://www.softwaresuggest.com/school-time-table-software	");
			url.add("	https://www.softwaresuggest.com/student-engagement-software	");
			url.add("	https://www.softwaresuggest.com/student-information-system	");
			url.add("	https://www.softwaresuggest.com/student-management-system	");
			url.add("	https://www.softwaresuggest.com/swim-school-software	");
			url.add("	https://www.softwaresuggest.com/test-management-tools	");
			url.add("	https://www.softwaresuggest.com/training-software	");
			url.add("	https://www.softwaresuggest.com/tutor-management-software	");
			url.add("	https://www.softwaresuggest.com/tutoring-software	");
			url.add("	https://www.softwaresuggest.com/admissions-software	");
			url.add("	https://www.softwaresuggest.com/alumni-management-software	");
			url.add("	https://www.softwaresuggest.com/assessment-examination-software	");
			url.add("	https://www.softwaresuggest.com/bookstore-software	");
			url.add("	https://www.softwaresuggest.com/campus-management-software	");
			url.add("	https://www.softwaresuggest.com/canteen-management-software	");
			url.add("	https://www.softwaresuggest.com/class-registration-software	");
			url.add("	https://www.softwaresuggest.com/classroom-management-software	");
			url.add("	https://www.softwaresuggest.com/coaching-class-software	");
			url.add("	https://www.softwaresuggest.com/colleges-universities-software	");
			url.add("	https://www.softwaresuggest.com/driving-school-software	");
			url.add("	https://www.softwaresuggest.com/driving-schools-software	");
			url.add("	https://www.softwaresuggest.com/dynamic-learning-training-software	");
			url.add("	https://www.softwaresuggest.com/e-learning-software	");
			url.add("	https://www.softwaresuggest.com/education-software	");
			url.add("	https://www.softwaresuggest.com/elearning-authoring-tools	");
			url.add("	https://www.softwaresuggest.com/exam-software	");
			url.add("	https://www.softwaresuggest.com/gradebook-software	");
			url.add("	https://www.softwaresuggest.com/interactive-teaching-software	");
			url.add("	https://www.softwaresuggest.com/learning-management-system	");
			url.add("	https://www.softwaresuggest.com/library-management-software	");
			url.add("	https://www.softwaresuggest.com/mentoring-software	");
			url.add("	https://www.softwaresuggest.com/micro-learning-software	");
			url.add("	https://www.softwaresuggest.com/music-school-software	");
			url.add("	https://www.softwaresuggest.com/online-assessment-software	");
			url.add("	https://www.softwaresuggest.com/online-training-software	");
			url.add("	https://www.softwaresuggest.com/scholarship-management-software	");
			url.add("	https://www.softwaresuggest.com/school-accounting-software	");
			url.add("	https://www.softwaresuggest.com/school-bus-routing-software	");
			url.add("	https://www.softwaresuggest.com/school-erp-software	");
			url.add("	https://www.softwaresuggest.com/quiz-maker-software	");
			url.add("	https://www.softwaresuggest.com/test-maker-software	");
			url.add("	https://www.softwaresuggest.com/electric-industry-software	");
			url.add("	https://www.softwaresuggest.com/electrical-contractor-software	");
			url.add("	https://www.softwaresuggest.com/electrical-estimating-software	");
			url.add("	https://www.softwaresuggest.com/electronics-and-appliance-software	");
			url.add("	https://www.softwaresuggest.com/hardware-and-paint-software	");
			url.add("	https://www.softwaresuggest.com/home-inspection-software	");
			url.add("	https://www.softwaresuggest.com/hvac-software	");
			url.add("	https://www.softwaresuggest.com/hvac-estimating-software	");
			url.add("	https://www.softwaresuggest.com/laundry-management-software	");
			url.add("	https://www.softwaresuggest.com/pest-control-software	");
			url.add("	https://www.softwaresuggest.com/plumbing-software	");
			url.add("	https://www.softwaresuggest.com/maid-service-software	");
			url.add("	https://www.softwaresuggest.com/plumbing-estimating-software	");
			url.add("	https://www.softwaresuggest.com/transactional-email-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-hr-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-mobility-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-search-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-social-networking-chatting-software	");
			url.add("	https://www.softwaresuggest.com/company-secretarial-software	");
			url.add("	https://www.softwaresuggest.com/corporate-wellness-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-architect-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-gamification-software	");
			url.add("	https://www.softwaresuggest.com/business-continuity-management-software	");
			url.add("	https://www.softwaresuggest.com/business-management-software	");
			url.add("	https://www.softwaresuggest.com/bpm-business-process-management-software	");
			url.add("	https://www.softwaresuggest.com/mis-software	");
			url.add("	https://www.softwaresuggest.com/erp-software	");
			url.add("	https://www.softwaresuggest.com/large-enterprise-erp-software	");
			url.add("	https://www.softwaresuggest.com/odoo-partner	");
			url.add("	https://www.softwaresuggest.com/sage-partner	");
			url.add("	https://www.softwaresuggest.com/sap-partner	");
			url.add("	https://www.softwaresuggest.com/small-business-erp-software	");
			url.add("	https://www.softwaresuggest.com/mrp-software	");
			url.add("	https://www.softwaresuggest.com/event-management-software	");
			url.add("	https://www.softwaresuggest.com/event-marketing-software	");
			url.add("	https://www.softwaresuggest.com/venue-management-software	");
			url.add("	https://www.softwaresuggest.com/sports-league-software	");
			url.add("	https://www.softwaresuggest.com/festival-management-software	");
			url.add("	https://www.softwaresuggest.com/tournament-software	");
			url.add("	https://www.softwaresuggest.com/wait-list-software	");
			url.add("	https://www.softwaresuggest.com/camp-management-software	");
			url.add("	https://www.softwaresuggest.com/event-booking-software	");
			url.add("	https://www.softwaresuggest.com/event-checkin-software	");
			url.add("	https://www.softwaresuggest.com/trade-show-software	");
			url.add("	https://www.softwaresuggest.com/registration-software	");
			url.add("	https://www.softwaresuggest.com/event-tracking-software	");
			url.add("	https://www.softwaresuggest.com/facility-management-software	");
			url.add("	https://www.softwaresuggest.com/lighting-energy-management-software	");
			url.add("	https://www.softwaresuggest.com/petrol-pump-software	");
			url.add("	https://www.softwaresuggest.com/queue-management-software	");
			url.add("	https://www.softwaresuggest.com/security-management-software	");
			url.add("	https://www.softwaresuggest.com/zoo-software	");
			url.add("	https://www.softwaresuggest.com/club-management-software	");
			url.add("	https://www.softwaresuggest.com/hostel-management-software	");
			url.add("	https://www.softwaresuggest.com/visitor-management-software	");
			url.add("	https://www.softwaresuggest.com/cemetery-software	");
			url.add("	https://www.softwaresuggest.com/financial-management-software	");
			url.add("	https://www.softwaresuggest.com/financial-fraud-detection-software	");
			url.add("	https://www.softwaresuggest.com/financial-reporting-software	");
			url.add("	https://www.softwaresuggest.com/financial-service-software	");
			url.add("	https://www.softwaresuggest.com/hedge-fund-software	");
			url.add("	https://www.softwaresuggest.com/investment-management-software	");
			url.add("	https://www.softwaresuggest.com/loan-management-software	");
			url.add("	https://www.softwaresuggest.com/loan-servicing-software	");
			url.add("	https://www.softwaresuggest.com/online-banking-software	");
			url.add("	https://www.softwaresuggest.com/payment-management-software	");
			url.add("	https://www.softwaresuggest.com/payment-processing-software	");
			url.add("	https://www.softwaresuggest.com/pci-compliance-software	");
			url.add("	https://www.softwaresuggest.com/personal-finance-software	");
			url.add("	https://www.softwaresuggest.com/policy-management-software	");
			url.add("	https://www.softwaresuggest.com/portfolio-management-software	");
			url.add("	https://www.softwaresuggest.com/reconciliation-software	");
			url.add("	https://www.softwaresuggest.com/stock-exchange-securities-market-software	");
			url.add("	https://www.softwaresuggest.com/telecom-expense-management-software	");
			url.add("	https://www.softwaresuggest.com/time-and-expense-software	");
			url.add("	https://www.softwaresuggest.com/treasury-software	");
			url.add("	https://www.softwaresuggest.com/waiver-software	");
			url.add("	https://www.softwaresuggest.com/currency-exchange-software	");
			url.add("	https://www.softwaresuggest.com/debt-collection-software	");
			url.add("	https://www.softwaresuggest.com/equity-management-software	");
			url.add("	https://www.softwaresuggest.com/expense-management-software	");
			url.add("	https://www.softwaresuggest.com/stock-brokerage-software	");
			url.add("	https://www.softwaresuggest.com/bankruptcy-software	");
			url.add("	https://www.softwaresuggest.com/claim-management-software	");
			url.add("	https://www.softwaresuggest.com/claims-processing-software	");
			url.add("	https://www.softwaresuggest.com/insurance-software	");
			url.add("	https://www.softwaresuggest.com/banking-industry-software	");
			url.add("	https://www.softwaresuggest.com/corporate-and-retail-banking-software	");
			url.add("	https://www.softwaresuggest.com/food-service-management-software	");
			url.add("	https://www.softwaresuggest.com/food-traceability-software	");
			url.add("	https://www.softwaresuggest.com/online-food-ordering-software	");
			url.add("	https://www.softwaresuggest.com/bakery-software	");
			url.add("	https://www.softwaresuggest.com/brewery-software	");
			url.add("	https://www.softwaresuggest.com/catering-management-software	");
			url.add("	https://www.softwaresuggest.com/food-delivery-software	");
			url.add("	https://www.softwaresuggest.com/food-service-distribution-software	");
			url.add("	https://www.softwaresuggest.com/government-software	");
			url.add("	https://www.softwaresuggest.com/identity-management-software	");
			url.add("	https://www.softwaresuggest.com/municipal-software	");
			url.add("	https://www.softwaresuggest.com/public-works-software	");
			url.add("	https://www.softwaresuggest.com/rto-agents-software	");
			url.add("	https://www.softwaresuggest.com/safety-management-software	");
			url.add("	https://www.softwaresuggest.com/subsidy-management-software	");
			url.add("	https://www.softwaresuggest.com/tender-management-software	");
			url.add("	https://www.softwaresuggest.com/voting-software	");
			url.add("	https://www.softwaresuggest.com/community-social-group-management-software	");
			url.add("	https://www.softwaresuggest.com/ehs-software	");
			url.add("	https://www.softwaresuggest.com/fire-department-software	");
			url.add("	https://www.softwaresuggest.com/forestry-tools	");
			url.add("	https://www.softwaresuggest.com/graphic-design-software	");
			url.add("	https://www.softwaresuggest.com/landscaping-software	");
			url.add("	https://www.softwaresuggest.com/org-chart-software	");
			url.add("	https://www.softwaresuggest.com/photo-editing-software	");
			url.add("	https://www.softwaresuggest.com/photo-studio-software	");
			url.add("	https://www.softwaresuggest.com/vector-graphics-software	");
			url.add("	https://www.softwaresuggest.com/web-design-software	");
			url.add("	https://www.softwaresuggest.com/whiteboard-animation-software	");
			url.add("	https://www.softwaresuggest.com/3d-design-software	");
			url.add("	https://www.softwaresuggest.com/animation-software	");
			url.add("	https://www.softwaresuggest.com/app-design-software	");
			url.add("	https://www.softwaresuggest.com/cad-software	");
			url.add("	https://www.softwaresuggest.com/catalog-management-software	");
			url.add("	https://www.softwaresuggest.com/clothing-design-software	");
			url.add("	https://www.softwaresuggest.com/designing-software	");
			url.add("	https://www.softwaresuggest.com/diagram-software	");
			url.add("	https://www.softwaresuggest.com/drawing-tools	");
			url.add("	https://www.softwaresuggest.com/fashion-designing-software	");
			url.add("	https://www.softwaresuggest.com/flowchart-software	");
			url.add("	https://www.softwaresuggest.com/gantt-chart-software	");
			url.add("	https://www.softwaresuggest.com/gis-software	");
			url.add("	https://www.softwaresuggest.com/business-card-design-software	");
			url.add("	https://www.softwaresuggest.com/pattern-making-software	");
			url.add("	https://www.softwaresuggest.com/photo-organizing-software	");
			url.add("	https://www.softwaresuggest.com/electric-design-software	");
			url.add("	https://www.softwaresuggest.com/hms-hotel-management-software	");
			url.add("	https://www.softwaresuggest.com/hotel-reservation-system	");
			url.add("	https://www.softwaresuggest.com/reservation-booking-system	");
			url.add("	https://www.softwaresuggest.com/restaurant-bar-software	");
			url.add("	https://www.softwaresuggest.com/restaurant-pos-software	");
			url.add("	https://www.softwaresuggest.com/hotel-front-desk-software	");
			url.add("	https://www.softwaresuggest.com/hospital-management-software	");
			url.add("	https://www.softwaresuggest.com/laboratory-information-management-system	");
			url.add("	https://www.softwaresuggest.com/long-term-care-software	");
			url.add("	https://www.softwaresuggest.com/medical-imaging-software	");
			url.add("	https://www.softwaresuggest.com/medical-practice-management-software	");
			url.add("	https://www.softwaresuggest.com/mr-reporting-software	");
			url.add("	https://www.softwaresuggest.com/medical-spa-software	");
			url.add("	https://www.softwaresuggest.com/medical-store-software	");
			url.add("	https://www.softwaresuggest.com/medical-transcription-software	");
			url.add("	https://www.softwaresuggest.com/nursing-home-software	");
			url.add("	https://www.softwaresuggest.com/nutrition-analysis-software	");
			url.add("	https://www.softwaresuggest.com/nutritionist-software	");
			url.add("	https://www.softwaresuggest.com/occupational-therapy-software	");
			url.add("	https://www.softwaresuggest.com/operating-system	");
			url.add("	https://www.softwaresuggest.com/optometry-software	");
			url.add("	https://www.softwaresuggest.com/pacs-software	");
			url.add("	https://www.softwaresuggest.com/patient-engagement-software	");
			url.add("	https://www.softwaresuggest.com/patient-management-software	");
			url.add("	https://www.softwaresuggest.com/patient-portal-software	");
			url.add("	https://www.softwaresuggest.com/pharma-erp-software	");
			url.add("	https://www.softwaresuggest.com/pharmacy-software	");
			url.add("	https://www.softwaresuggest.com/physical-therapy-software	");
			url.add("	https://www.softwaresuggest.com/plastic-surgery-software	");
			url.add("	https://www.softwaresuggest.com/podiatry-software	");
			url.add("	https://www.softwaresuggest.com/practice-management-software	");
			url.add("	https://www.softwaresuggest.com/radiology-software	");
			url.add("	https://www.softwaresuggest.com/speech-therapy-software	");
			url.add("	https://www.softwaresuggest.com/telemedicine-software	");
			url.add("	https://www.softwaresuggest.com/trial-management-software	");
			url.add("	https://www.softwaresuggest.com/veterinary-software	");
			url.add("	https://www.softwaresuggest.com/child-care-software	");
			url.add("	https://www.softwaresuggest.com/chiropractice-software	");
			url.add("	https://www.softwaresuggest.com/clinical-trial-management-software	");
			url.add("	https://www.softwaresuggest.com/credentialing-software	");
			url.add("	https://www.softwaresuggest.com/dental-software	");
			url.add("	https://www.softwaresuggest.com/dermatology-software	");
			url.add("	https://www.softwaresuggest.com/doctor-software	");
			url.add("	https://www.softwaresuggest.com/e-prescribing-software	");
			url.add("	https://www.softwaresuggest.com/electronic-medical-record-software	");
			url.add("	https://www.softwaresuggest.com/emr-clinic-management-software	");
			url.add("	https://www.softwaresuggest.com/ems-software	");
			url.add("	https://www.softwaresuggest.com/healthcare-software	");
			url.add("	https://www.softwaresuggest.com/healthcare-crm-software	");
			url.add("	https://www.softwaresuggest.com/home-health-software	");
			url.add("	https://www.softwaresuggest.com/hospice-software	");
			url.add("	https://www.softwaresuggest.com/lab-management-software	");
			url.add("	https://www.softwaresuggest.com/pharmaceutical-industry-software	");
			url.add("	https://www.softwaresuggest.com/pediatric-software	");
			url.add("	https://www.softwaresuggest.com/hr-software	");
			url.add("	https://www.softwaresuggest.com/hr-analytics-software	");
			url.add("	https://www.softwaresuggest.com/hr-consulting-services	");
			url.add("	https://www.softwaresuggest.com/hr-gamification-software	");
			url.add("	https://www.softwaresuggest.com/hr-mobile-apps-software	");
			url.add("	https://www.softwaresuggest.com/hr-outsourcing-services	");
			url.add("	https://www.softwaresuggest.com/human-capital-management-software	");
			url.add("	https://www.softwaresuggest.com/human-service-software	");
			url.add("	https://www.softwaresuggest.com/job-board-software	");
			url.add("	https://www.softwaresuggest.com/job-costing-software	");
			url.add("	https://www.softwaresuggest.com/job-evaluation-software	");
			url.add("	https://www.softwaresuggest.com/job-portal-script-software	");
			url.add("	https://www.softwaresuggest.com/job-shop-software	");
			url.add("	https://www.softwaresuggest.com/leave-management-software	");
			url.add("	https://www.softwaresuggest.com/medium-sized-business-hr-software	");
			url.add("	https://www.softwaresuggest.com/okr-software	");
			url.add("	https://www.softwaresuggest.com/payroll-software	");
			url.add("	https://www.softwaresuggest.com/payroll-outsourcing-services	");
			url.add("	https://www.softwaresuggest.com/performance-appraisal-software	");
			url.add("	https://www.softwaresuggest.com/performance-management-system	");
			url.add("	https://www.softwaresuggest.com/personnel-software	");
			url.add("	https://www.softwaresuggest.com/pre-employment-testing-software	");
			url.add("	https://www.softwaresuggest.com/productivity-management-software	");
			url.add("	https://www.softwaresuggest.com/recruiting-agency-software	");
			url.add("	https://www.softwaresuggest.com/recruiting-software	");
			url.add("	https://www.softwaresuggest.com/reference-management-software	");
			url.add("	https://www.softwaresuggest.com/small-business-hr-software	");
			url.add("	https://www.softwaresuggest.com/staffing-software	");
			url.add("	https://www.softwaresuggest.com/staffing-agency-software	");
			url.add("	https://www.softwaresuggest.com/succession-planning-software	");
			url.add("	https://www.softwaresuggest.com/talent-management-system	");
			url.add("	https://www.softwaresuggest.com/time-clock-software	");
			url.add("	https://www.softwaresuggest.com/video-interview-software	");
			url.add("	https://www.softwaresuggest.com/workforce-management-software	");
			url.add("	https://www.softwaresuggest.com/360-degree-feedback-software	");
			url.add("	https://www.softwaresuggest.com/absence-management-system	");
			url.add("	https://www.softwaresuggest.com/applicant-tracking-system	");
			url.add("	https://www.softwaresuggest.com/attendance-management-software	");
			url.add("	https://www.softwaresuggest.com/background-verification-software	");
			url.add("	https://www.softwaresuggest.com/benefits-administration-software	");
			url.add("	https://www.softwaresuggest.com/biometric-attendance-system	");
			url.add("	https://www.softwaresuggest.com/compensation-management-software	");
			url.add("	https://www.softwaresuggest.com/employee-communication-tools	");
			url.add("	https://www.softwaresuggest.com/employee-engagement-software	");
			url.add("	https://www.softwaresuggest.com/employee-management-software	");
			url.add("	https://www.softwaresuggest.com/employee-monitoring-software	");
			url.add("	https://www.softwaresuggest.com/employee-onboarding-software	");
			url.add("	https://www.softwaresuggest.com/employee-recognition-software	");
			url.add("	https://www.softwaresuggest.com/employee-scheduling-software	");
			url.add("	https://www.softwaresuggest.com/employee-tracking-system	");
			url.add("	https://www.softwaresuggest.com/employee-transport-management-software	");
			url.add("	https://www.softwaresuggest.com/payslip-software	");
			url.add("	https://www.softwaresuggest.com/inventory-management-software	");
			url.add("	https://www.softwaresuggest.com/stock-management-software	");
			url.add("	https://www.softwaresuggest.com/ecommerce-inventory-management-software	");
			url.add("	https://www.softwaresuggest.com/warehouse-management-software	");
			url.add("	https://www.softwaresuggest.com/it-service-management-software	");
			url.add("	https://www.softwaresuggest.com/itsm-software	");
			url.add("	https://www.softwaresuggest.com/mac-protection-software	");
			url.add("	https://www.softwaresuggest.com/msp-software	");
			url.add("	https://www.softwaresuggest.com/network-mapping-software	");
			url.add("	https://www.softwaresuggest.com/network-monitoring-software	");
			url.add("	https://www.softwaresuggest.com/network-security-software	");
			url.add("	https://www.softwaresuggest.com/network-troubleshooting-software	");
			url.add("	https://www.softwaresuggest.com/password-management-software	");
			url.add("	https://www.softwaresuggest.com/performance-testing-tools	");
			url.add("	https://www.softwaresuggest.com/server-backup-software	");
			url.add("	https://www.softwaresuggest.com/service-desk-management-software	");
			url.add("	https://www.softwaresuggest.com/siem-software	");
			url.add("	https://www.softwaresuggest.com/single-sign-on-software	");
			url.add("	https://www.softwaresuggest.com/software-it-software	");
			url.add("	https://www.softwaresuggest.com/vpn-software	");
			url.add("	https://www.softwaresuggest.com/click-fraud-software	");
			url.add("	https://www.softwaresuggest.com/digital-rights-management-software	");
			url.add("	https://www.softwaresuggest.com/email-security-software	");
			url.add("	https://www.softwaresuggest.com/emergency-notification-software	");
			url.add("	https://www.softwaresuggest.com/extranet-software	");
			url.add("	https://www.softwaresuggest.com/fax-server-software	");
			url.add("	https://www.softwaresuggest.com/it-outsourcing-services	");
			url.add("	https://www.softwaresuggest.com/authentication-software	");
			url.add("	https://www.softwaresuggest.com/vulnerability-management-tools	");
			url.add("	https://www.softwaresuggest.com/load-testing-tools	");
			url.add("	https://www.softwaresuggest.com/legal-case-management-software	");
			url.add("	https://www.softwaresuggest.com/license-management-software	");
			url.add("	https://www.softwaresuggest.com/litigation-management-software	");
			url.add("	https://www.softwaresuggest.com/accreditation-management-software	");
			url.add("	https://www.softwaresuggest.com/code-enforcement-software	");
			url.add("	https://www.softwaresuggest.com/conflict-check-software	");
			url.add("	https://www.softwaresuggest.com/court-management-software	");
			url.add("	https://www.softwaresuggest.com/docket-system	");
			url.add("	https://www.softwaresuggest.com/electronic-discovery-software	");
			url.add("	https://www.softwaresuggest.com/incident-management-software	");
			url.add("	https://www.softwaresuggest.com/investigation-management-software	");
			url.add("	https://www.softwaresuggest.com/issue-tracking-software	");
			url.add("	https://www.softwaresuggest.com/jail-management-software	");
			url.add("	https://www.softwaresuggest.com/law-enforcement-software	");
			url.add("	https://www.softwaresuggest.com/law-firm-advocates-software	");
			url.add("	https://www.softwaresuggest.com/lawn-care-software	");
			url.add("	https://www.softwaresuggest.com/legal-calendaring-software	");
			url.add("	https://www.softwaresuggest.com/compliance-management-software	");
			url.add("	https://www.softwaresuggest.com/grc-software	");
			url.add("	https://www.softwaresuggest.com/manufacturing-software	");
			url.add("	https://www.softwaresuggest.com/material-management-software	");
			url.add("	https://www.softwaresuggest.com/mes-system	");
			url.add("	https://www.softwaresuggest.com/oee-software	");
			url.add("	https://www.softwaresuggest.com/product-configurator-software	");
			url.add("	https://www.softwaresuggest.com/prototyping-software	");
			url.add("	https://www.softwaresuggest.com/quality-control-software	");
			url.add("	https://www.softwaresuggest.com/recycling-software	");
			url.add("	https://www.softwaresuggest.com/resource-management-software	");
			url.add("	https://www.softwaresuggest.com/spc-software	");
			url.add("	https://www.softwaresuggest.com/tool-management-software	");
			url.add("	https://www.softwaresuggest.com/valve-manufacturing-software	");
			url.add("	https://www.softwaresuggest.com/demand-planning-software	");
			url.add("	https://www.softwaresuggest.com/dock-scheduling-software	");
			url.add("	https://www.softwaresuggest.com/inspection-software	");
			url.add("	https://www.softwaresuggest.com/label-printing-software	");
			url.add("	https://www.softwaresuggest.com/equipment-maintenance-software	");
			url.add("	https://www.softwaresuggest.com/marketing-automation-software	");
			url.add("	https://www.softwaresuggest.com/marketing-planning-software	");
			url.add("	https://www.softwaresuggest.com/mlm-software	");
			url.add("	https://www.softwaresuggest.com/mobile-marketing-platform-software	");
			url.add("	https://www.softwaresuggest.com/mrm-marketing-resource-management-software	");
			url.add("	https://www.softwaresuggest.com/online-campaign-management-software	");
			url.add("	https://www.softwaresuggest.com/political-campaign-system	");
			url.add("	https://www.softwaresuggest.com/ppc-software	");
			url.add("	https://www.softwaresuggest.com/pr-software	");
			url.add("	https://www.softwaresuggest.com/publication-and-printing-software	");
			url.add("	https://www.softwaresuggest.com/push-notification-services	");
			url.add("	https://www.softwaresuggest.com/referral-software	");
			url.add("	https://www.softwaresuggest.com/reputation-management-software	");
			url.add("	https://www.softwaresuggest.com/retargeting-software	");
			url.add("	https://www.softwaresuggest.com/scheduling-software	");
			url.add("	https://www.softwaresuggest.com/seo-software	");
			url.add("	https://www.softwaresuggest.com/social-media-analytics-tools	");
			url.add("	https://www.softwaresuggest.com/social-media-management-software	");
			url.add("	https://www.softwaresuggest.com/social-media-marketing-software	");
			url.add("	https://www.softwaresuggest.com/social-network-software	");
			url.add("	https://www.softwaresuggest.com/subscription-management-software	");
			url.add("	https://www.softwaresuggest.com/trade-promotion-management-software	");
			url.add("	https://www.softwaresuggest.com/url-shortener-tools	");
			url.add("	https://www.softwaresuggest.com/whatsapp-marketing-software	");
			url.add("	https://www.softwaresuggest.com/account-based-marketing-software	");
			url.add("	https://www.softwaresuggest.com/advertising-agency-software	");
			url.add("	https://www.softwaresuggest.com/affiliate-software	");
			url.add("	https://www.softwaresuggest.com/brand-management-software	");
			url.add("	https://www.softwaresuggest.com/brand-protection-software	");
			url.add("	https://www.softwaresuggest.com/bulk-sms-software	");
			url.add("	https://www.softwaresuggest.com/business-email-software	");
			url.add("	https://www.softwaresuggest.com/channel-management-software	");
			url.add("	https://www.softwaresuggest.com/content-marketing-software	");
			url.add("	https://www.softwaresuggest.com/contest-software	");
			url.add("	https://www.softwaresuggest.com/conversational-marketing-software	");
			url.add("	https://www.softwaresuggest.com/conversion-optimization-tools	");
			url.add("	https://www.softwaresuggest.com/creative-management-platform-software	");
			url.add("	https://www.softwaresuggest.com/digital-marketing-software	");
			url.add("	https://www.softwaresuggest.com/digital-signage-software	");
			url.add("	https://www.softwaresuggest.com/drip-email-marketing-software	");
			url.add("	https://www.softwaresuggest.com/email-marketing-software	");
			url.add("	https://www.softwaresuggest.com/email-signature-software	");
			url.add("	https://www.softwaresuggest.com/email-tracking-software	");
			url.add("	https://www.softwaresuggest.com/email-verification-tools	");
			url.add("	https://www.softwaresuggest.com/influencer-marketing-software	");
			url.add("	https://www.softwaresuggest.com/link-management-tools	");
			url.add("	https://www.softwaresuggest.com/link-tracking-software	");
			url.add("	https://www.softwaresuggest.com/mailroom-management-software	");
			url.add("	https://www.softwaresuggest.com/market-research-software	");
			url.add("	https://www.softwaresuggest.com/marketing-analytics-tools	");
			url.add("	https://www.softwaresuggest.com/marketing-attribution-software	");
			url.add("	https://www.softwaresuggest.com/ad-server-software	");
			url.add("	https://www.softwaresuggest.com/fundraising-software	");
			url.add("	https://www.softwaresuggest.com/grant-management-software	");
			url.add("	https://www.softwaresuggest.com/volunteer-management-software	");
			url.add("	https://www.softwaresuggest.com/worship-software	");
			url.add("	https://www.softwaresuggest.com/animal-shelter-software	");
			url.add("	https://www.softwaresuggest.com/church-management-software	");
			url.add("	https://www.softwaresuggest.com/church-presentation-software	");
			url.add("	https://www.softwaresuggest.com/donor-management-software	");
			url.add("	https://www.softwaresuggest.com/nonprofit-software	");
			url.add("	https://www.softwaresuggest.com/operations-management-software	");
			url.add("	https://www.softwaresuggest.com/plant-maintenance-software	");
			url.add("	https://www.softwaresuggest.com/preventive-maintenance-software	");
			url.add("	https://www.softwaresuggest.com/waste-management-software	");
			url.add("	https://www.softwaresuggest.com/water-management-software	");
			url.add("	https://www.softwaresuggest.com/work-order-software	");
			url.add("	https://www.softwaresuggest.com/change-management-software	");
			url.add("	https://www.softwaresuggest.com/cmms-software	");
			url.add("	https://www.softwaresuggest.com/contract-management-software	");
			url.add("	https://www.softwaresuggest.com/corrective-and-preventive-action-capa-software	");
			url.add("	https://www.softwaresuggest.com/key-management-software	");
			url.add("	https://www.softwaresuggest.com/log-book-software	");
			url.add("	https://www.softwaresuggest.com/log-management-software	");
			url.add("	https://www.softwaresuggest.com/lost-and-found-software	");
			url.add("	https://www.softwaresuggest.com/maintenance-management-software	");
			url.add("	https://www.softwaresuggest.com/office-management-software	");
			url.add("	https://www.softwaresuggest.com/risk-management-software	");
			url.add("	https://www.softwaresuggest.com/sourcing-software	");
			url.add("	https://www.softwaresuggest.com/eprocurement-software	");
			url.add("	https://www.softwaresuggest.com/purchasing-software	");
			url.add("	https://www.softwaresuggest.com/supply-chain-management-software	");
			url.add("	https://www.softwaresuggest.com/pet-grooming-software	");
			url.add("	https://www.softwaresuggest.com/pet-sitting-software	");
			url.add("	https://www.softwaresuggest.com/horse-software	");
			url.add("	https://www.softwaresuggest.com/kennel-software	");
			url.add("	https://www.softwaresuggest.com/project-management-software	");
			url.add("	https://www.softwaresuggest.com/project-planning-software	");
			url.add("	https://www.softwaresuggest.com/project-portfolio-management-software	");
			url.add("	https://www.softwaresuggest.com/project-tracking-software	");
			url.add("	https://www.softwaresuggest.com/strategic-planning-software	");
			url.add("	https://www.softwaresuggest.com/survey-software	");
			url.add("	https://www.softwaresuggest.com/task-management-software	");
			url.add("	https://www.softwaresuggest.com/time-management-software	");
			url.add("	https://www.softwaresuggest.com/time-table-management-software	");
			url.add("	https://www.softwaresuggest.com/time-tracking-software	");
			url.add("	https://www.softwaresuggest.com/it-project-management-software	");
			url.add("	https://www.softwaresuggest.com/predictive-analytics-software	");
			url.add("	https://www.softwaresuggest.com/product-management-software	");
			url.add("	https://www.softwaresuggest.com/product-roadmap-software	");
			url.add("	https://www.softwaresuggest.com/plm-software	");
			url.add("	https://www.softwaresuggest.com/workflow-management-software	");
			url.add("	https://www.softwaresuggest.com/form-automation-software	");
			url.add("	https://www.softwaresuggest.com/professional-service-automation-software	");
			url.add("	https://www.softwaresuggest.com/workload-automation-software	");
			url.add("	https://www.softwaresuggest.com/property-management-software	");
			url.add("	https://www.softwaresuggest.com/quotation-management-software	");
			url.add("	https://www.softwaresuggest.com/real-estate-software	");
			url.add("	https://www.softwaresuggest.com/real-estate-crm-software	");
			url.add("	https://www.softwaresuggest.com/rental-software	");
			url.add("	https://www.softwaresuggest.com/space-management-software	");
			url.add("	https://www.softwaresuggest.com/yard-management-system	");
			url.add("	https://www.softwaresuggest.com/utility-software	");
			url.add("	https://www.softwaresuggest.com/timeshare-system	");
			url.add("	https://www.softwaresuggest.com/surveillance-software	");
			url.add("	https://www.softwaresuggest.com/shop-floor-management-software	");
			url.add("	https://www.softwaresuggest.com/rera-filing-compliance-software	");
			url.add("	https://www.softwaresuggest.com/remodeling-estimating-software	");
			url.add("	https://www.softwaresuggest.com/housing-society-apartments-software	");
			url.add("	https://www.softwaresuggest.com/assisted-living-software	");
			url.add("	https://www.softwaresuggest.com/auction-software	");
			url.add("	https://www.softwaresuggest.com/bim-software	");
			url.add("	https://www.softwaresuggest.com/building-maintenance-management-software	");
			url.add("	https://www.softwaresuggest.com/campground-management-software	");
			url.add("	https://www.softwaresuggest.com/hoa-software	");
			url.add("	https://www.softwaresuggest.com/golf-course-software	");
			url.add("	https://www.softwaresuggest.com/home-builder-software	");
			url.add("	https://www.softwaresuggest.com/infrastructure-software	");
			url.add("	https://www.softwaresuggest.com/intellectual-property-software	");
			url.add("	https://www.softwaresuggest.com/land-management-system	");
			url.add("	https://www.softwaresuggest.com/parking-management-software	");
			url.add("	https://www.softwaresuggest.com/parks-and-recreation-software	");
			url.add("	https://www.softwaresuggest.com/physical-security-software	");
			url.add("	https://www.softwaresuggest.com/membership-management-software	");
			url.add("	https://www.softwaresuggest.com/museum-software	");
			url.add("	https://www.softwaresuggest.com/personal-training-software	");
			url.add("	https://www.softwaresuggest.com/pilates-studio-software	");
			url.add("	https://www.softwaresuggest.com/tattoo-studio-software	");
			url.add("	https://www.softwaresuggest.com/tour-travel-operator-software	");
			url.add("	https://www.softwaresuggest.com/travel-management-software	");
			url.add("	https://www.softwaresuggest.com/workshop-management-software	");
			url.add("	https://www.softwaresuggest.com/yoga-studio-software	");
			url.add("	https://www.softwaresuggest.com/gymnastics-software	");
			url.add("	https://www.softwaresuggest.com/martial-arts-software	");
			url.add("	https://www.softwaresuggest.com/massage-therapy-software	");
			url.add("	https://www.softwaresuggest.com/art-gallery-software	");
			url.add("	https://www.softwaresuggest.com/dance-studio-software	");
			url.add("	https://www.softwaresuggest.com/fitness-club-gym-management-software	");
			url.add("	https://www.softwaresuggest.com/spa-salon-software	");
			url.add("	https://www.softwaresuggest.com/ayurvedic-software	");
			url.add("	https://www.softwaresuggest.com/retail-software	");
			url.add("	https://www.softwaresuggest.com/service-professional-and-agents-software	");
			url.add("	https://www.softwaresuggest.com/shop-management-software	");
			url.add("	https://www.softwaresuggest.com/store-locator-software	");
			url.add("	https://www.softwaresuggest.com/supermarket-software	");
			url.add("	https://www.softwaresuggest.com/tailoring-software	");
			url.add("	https://www.softwaresuggest.com/convenience-store-software	");
			url.add("	https://www.softwaresuggest.com/departmental-store-software	");
			url.add("	https://www.softwaresuggest.com/fmcg-software	");
			url.add("	https://www.softwaresuggest.com/grocery-store-pos-system	");
			url.add("	https://www.softwaresuggest.com/mandi-software	");
			url.add("	https://www.softwaresuggest.com/mobile-store-software	");
			url.add("	https://www.softwaresuggest.com/point-of-sale-pos-software	");
			url.add("	https://www.softwaresuggest.com/publishing-subscriptions-software	");
			url.add("	https://www.softwaresuggest.com/retail-pos-software	");
			url.add("	https://www.softwaresuggest.com/auto-dealer-software	");
			url.add("	https://www.softwaresuggest.com/barcode-software	");
			url.add("	https://www.softwaresuggest.com/cheque-printing-software	");
			url.add("	https://www.softwaresuggest.com/apparel-garment-footwear-software	");
			url.add("	https://www.softwaresuggest.com/optical-shop-software	");
			url.add("	https://www.softwaresuggest.com/pos-billing-software	");
			url.add("	https://www.softwaresuggest.com/retail-billing-software	");
			url.add("	https://www.softwaresuggest.com/auto-repair-software	");
			url.add("	https://www.softwaresuggest.com/oracle-partner	");
			url.add("	https://www.softwaresuggest.com/ibm-partner	");
			url.add("	https://www.softwaresuggest.com/infor-partner	");
			url.add("	https://www.softwaresuggest.com/adobe-partner	");
			url.add("	https://www.softwaresuggest.com/cisco-partner	");
			url.add("	https://www.softwaresuggest.com/salesforce-partner	");
			url.add("	https://www.softwaresuggest.com/epicor-partner	");
			url.add("	https://www.softwaresuggest.com/tally-partner	");
			url.add("	https://www.softwaresuggest.com/sales-management-software	");
			url.add("	https://www.softwaresuggest.com/sales-productivity-software	");
			url.add("	https://www.softwaresuggest.com/social-selling-tools	");
			url.add("	https://www.softwaresuggest.com/client-management-software	");
			url.add("	https://www.softwaresuggest.com/commission-management-software	");
			url.add("	https://www.softwaresuggest.com/cpq-software	");
			url.add("	https://www.softwaresuggest.com/lead-generation-software	");
			url.add("	https://www.softwaresuggest.com/lead-management-system	");
			url.add("	https://www.softwaresuggest.com/lead-nurturing-software	");
			url.add("	https://www.softwaresuggest.com/pricing-optimization-software	");
			url.add("	https://www.softwaresuggest.com/proposal-management-software	");
			url.add("	https://www.softwaresuggest.com/quoting-software	");
			url.add("	https://www.softwaresuggest.com/revenue-management-software	");
			url.add("	https://www.softwaresuggest.com/rfp-software	");
			url.add("	https://www.softwaresuggest.com/sales-analytics-crm-software	");
			url.add("	https://www.softwaresuggest.com/sales-enablement-software	");
			url.add("	https://www.softwaresuggest.com/sales-engagement-software	");
			url.add("	https://www.softwaresuggest.com/sales-forecasting-software	");
			url.add("	https://www.softwaresuggest.com/sales-intelligence-software	");
			url.add("	https://www.softwaresuggest.com/sfa-sales-force-automation-software	");
			url.add("	https://www.softwaresuggest.com/sales-coaching-software	");
			url.add("	https://www.softwaresuggest.com/field-force-automation-software	");
			url.add("	https://www.softwaresuggest.com/lead-scoring-software	");
			url.add("	https://www.softwaresuggest.com/field-service-management-software	");
			url.add("	https://www.softwaresuggest.com/taxi-script-software	");
			url.add("	https://www.softwaresuggest.com/clone-scripts	");
			url.add("	https://www.softwaresuggest.com/hotel-booking-engine-software	");
			url.add("	https://www.softwaresuggest.com/social-media-scripts	");
			url.add("	https://www.softwaresuggest.com/directory-scripts	");
			url.add("	https://www.softwaresuggest.com/uber-for-x-software	");
			url.add("	https://www.softwaresuggest.com/transport-management-software	");
			url.add("	https://www.softwaresuggest.com/vehicle-tracking-system	");
			url.add("	https://www.softwaresuggest.com/car-rental-software	");
			url.add("	https://www.softwaresuggest.com/consignment-software	");
			url.add("	https://www.softwaresuggest.com/courier-management-software	");
			url.add("	https://www.softwaresuggest.com/delivery-management-software	");
			url.add("	https://www.softwaresuggest.com/fleet-management-software	");
			url.add("	https://www.softwaresuggest.com/freight-software	");
			url.add("	https://www.softwaresuggest.com/fuel-management-system	");
			url.add("	https://www.softwaresuggest.com/garage-management-software	");
			url.add("	https://www.softwaresuggest.com/gps-tracking-system	");
			url.add("	https://www.softwaresuggest.com/handyman-software	");
			url.add("	https://www.softwaresuggest.com/location-intelligence-software	");
			url.add("	https://www.softwaresuggest.com/logistics-industry-software	");
			url.add("	https://www.softwaresuggest.com/moving-software	");
			url.add("	https://www.softwaresuggest.com/order-management-software	");
			url.add("	https://www.softwaresuggest.com/pool-service-software	");
			url.add("	https://www.softwaresuggest.com/relocation-software	");
			url.add("	https://www.softwaresuggest.com/route-planning-software	");
			url.add("	https://www.softwaresuggest.com/self-storage-software	");
			url.add("	https://www.softwaresuggest.com/service-dispatch-software	");
			url.add("	https://www.softwaresuggest.com/shipment-tracking-software	");
			url.add("	https://www.softwaresuggest.com/shipping-software	");
			url.add("	https://www.softwaresuggest.com/towing-software	");
			url.add("	https://www.softwaresuggest.com/airline-reservation-system	");
			url.add("	https://www.softwaresuggest.com/automobile-industry-software	");
			url.add("	https://www.softwaresuggest.com/printing-packaging-industry-software	");
			url.add("	https://www.softwaresuggest.com/marine-software	");
			url.add("	https://www.softwaresuggest.com/weighbridge-software	");
			url.add("	https://www.softwaresuggest.com/enterprise-vehicle-management-software	");
			url.add("	https://www.softwaresuggest.com/autobody-software	");
			url.add("	https://www.softwaresuggest.com/taxation-software	");
			url.add("	https://www.softwaresuggest.com/trading-software	");
			url.add("	https://www.softwaresuggest.com/vat-software	");
			url.add("	https://www.softwaresuggest.com/audit-management-software	");
			url.add("	https://www.softwaresuggest.com/corporate-tax-software	");
			url.add("	https://www.softwaresuggest.com/income-tax-software	");
			url.add("	https://www.softwaresuggest.com/sales-tax-software	");
			url.add("	https://www.softwaresuggest.com/tax-preparation-software	");
			url.add("	https://www.softwaresuggest.com/agriculture-tools	");
			url.add("	https://www.softwaresuggest.com/chemical-industry-software	");
			url.add("	https://www.softwaresuggest.com/dairy-industry-software	");
			url.add("	https://www.softwaresuggest.com/engineering-industry-software	");
			url.add("	https://www.softwaresuggest.com/glass-industry-software	");
			url.add("	https://www.softwaresuggest.com/mining-software	");
			url.add("	https://www.softwaresuggest.com/oil-and-gas-software	");
			url.add("	https://www.softwaresuggest.com/petroleum-industry-software	");
			url.add("	https://www.softwaresuggest.com/plastic-industry-software	");
			url.add("	https://www.softwaresuggest.com/plywood-timber-wood-industry-software	");
			url.add("	https://www.softwaresuggest.com/video-making-software	");
			url.add("	https://www.softwaresuggest.com/video-management-software	");
			url.add("	https://www.softwaresuggest.com/video-editing-software	");
			url.add("	https://www.softwaresuggest.com/streaming-software	");
			url.add("	https://www.softwaresuggest.com/screen-recording-software	");
			url.add("	https://www.softwaresuggest.com/video-recovery-software	");
			url.add("	https://www.softwaresuggest.com/website-builder-services	");
			url.add("	https://www.softwaresuggest.com/website-development-software	");
			url.add("	https://www.softwaresuggest.com/website-monitoring-software	");
			url.add("	https://www.softwaresuggest.com/website-optimization-tools	");
			url.add("	https://www.softwaresuggest.com/cloud-hosting-services	");
			url.add("	https://www.softwaresuggest.com/cloud-management-software	");
			url.add("	https://www.softwaresuggest.com/ecommerce-tools	");
			url.add("	https://www.softwaresuggest.com/ecommerce-platform-software	");
			url.add("	https://www.softwaresuggest.com/exit-intent-popup-software	");
			url.add("	https://www.softwaresuggest.com/landing-page-software	");
			url.add("	https://www.softwaresuggest.com/multi-channel-ecommerce-software	");
			url.add("	https://www.softwaresuggest.com/payment-gateway-services	");
			url.add("	https://www.softwaresuggest.com/portal-software	");
			url.add("	https://www.softwaresuggest.com/shopping-cart-software	");
			url.add("	https://www.softwaresuggest.com/ux-software	");
			url.add("	https://www.softwaresuggest.com/ux-design-tools	");
			url.add("	https://www.softwaresuggest.com/web-analytics-software	");
			url.add("	https://www.softwaresuggest.com/dashboard-software	");
			url.add("	https://www.softwaresuggest.com/online-marketplace-software	");
			url.add("	https://www.softwaresuggest.com/personalization-software	");
			url.add("	https://www.softwaresuggest.com/arborist-software	");
			url.add("	https://www.softwaresuggest.com/aviation-maintenance-software	");
			url.add("	https://www.softwaresuggest.com/cable-tv-software	");
			url.add("	https://www.softwaresuggest.com/consultancy-software	");
			url.add("	https://www.softwaresuggest.com/custom-software	");
			url.add("	https://www.softwaresuggest.com/decision-support-software	");
			url.add("	https://www.softwaresuggest.com/florist-software	");
			url.add("	https://www.softwaresuggest.com/funeral-home-software	");
			url.add("	https://www.softwaresuggest.com/idea-management-software	");
			url.add("	https://www.softwaresuggest.com/innovation-software	");
			url.add("	https://www.softwaresuggest.com/jewellery-software	");
			url.add("	https://www.softwaresuggest.com/mind-map-software	");
			url.add("	https://www.softwaresuggest.com/mobile-recharge-software	");
			url.add("	https://www.softwaresuggest.com/mobility-software	");
			url.add("	https://www.softwaresuggest.com/optimisation-software	");
			url.add("	https://www.softwaresuggest.com/sustainability-software	");
			url.add("	https://www.softwaresuggest.com/calibration-software	");
			url.add("	https://www.softwaresuggest.com/warranty-management-software	");
			url.add("	https://www.softwaresuggest.com/appointment-management-system	");
			url.add("	https://www.softwaresuggest.com/appointment-scheduling-software	");
			url.add("	https://www.softwaresuggest.com/association-management-software	");
			url.add("	https://www.softwaresuggest.com/cannabis-software	");
			url.add("	https://www.softwaresuggest.com/industry-management-software	");
			url.add("	https://www.softwaresuggest.com/janitor-software	");
			url.add("	https://www.softwaresuggest.com/farm-management-software	");
			String categoryname=null;
			
			
			for (String string : url) 
			{ 
				
				try{
					Thread.sleep(1000);
					String urlLink= string.toString().trim();
				    categoryname=urlLink.replace("https://www.softwaresuggest.com/", "");
					companyPage=getCompanyPage(chromeDriver,urlLink);

					By inputArea1 = By.xpath("//div[@class='view_more_btn_div old_filter_view_more']/button");
					if(isElementPresent(companyPage,inputArea1));
					{

						element = companyPage.findElement(inputArea1);
				
						//JavascriptExecutor executor = (JavascriptExecutor)companyPage;
						//executor.executeScript("arguments[0].click();", element);
						for (int i = 1; i < 100; i++) {
							Actions actions = new Actions(companyPage);
							actions.moveToElement(element).click().build().perform();
							Thread.sleep(1000);
							JavascriptExecutor js = (JavascriptExecutor) companyPage;
							//js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
							js.executeScript("arguments[0].click();", element);
							// js.executeScript("window.scrollBy(0,100)");
						}
					
					}
					String resp=companyPage.getPageSource();
					if(!resp.equals(""))
					{				
						try {	

							Files.write(Paths.get("C:\\OM\\softwaresuggest\\"+categoryname+".html"), resp.getBytes());
						} catch (IOException e) {
							e.printStackTrace();
						}
					}
					
				} catch (Exception e) {
					String resp=companyPage.getPageSource();
					if(!resp.equals(""))
					{				
						try {	

							Files.write(Paths.get("C:\\OM\\softwaresuggest\\"+categoryname+".html"), resp.getBytes());
						} catch (IOException ea) {
							ea.printStackTrace();
						}
					}
				}
			}

		}
	}



	public static WebDriver getCompanyPage(WebDriver driver,String url)
	{	
		try
		{
			driver.navigate().to(url);

		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		return driver;
	}


	public static WebDriver setChromeDriver() 
	{
		WebDriver driver = null;
		ChromeOptions options = null;
		try {
			options = new ChromeOptions();
			options.addArguments("--window-size=2000,6000");
			System.setProperty("webdriver.chrome.driver", "C:\\Om\\drivers\\chromedriver_win32\\chromedriver.exe");
			driver = new ChromeDriver(options);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return driver;
	}

	public static boolean isElementPresent(WebDriver driver ,By selector)
	{
		return driver.findElements(selector).size()>0;
	}
}
